services:
  mongodb:
    image: mongo:7
    container_name: yzj-mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - ./.local/mongodb:/data/db

  qdrant:
    image: qdrant/qdrant:latest
    container_name: yzj-qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./.local/qdrant:/qdrant/storage
