import type {
  AssetPageConfig,
  AssistantScene,
  AudioImportTask,
  ConversationSession,
  PageMetric,
  RankingItem,
  RecordPageConfig,
  ResearchSnapshot,
  SceneTask,
  SettingPageConfig,
  SystemAlert,
  SystemHealthItem,
  TenantContext,
  ToolRegistryItem,
  TraceLog,
  TrendPoint,
  VisitBrief,
  WritebackPolicy,
  SkillCatalogItem,
} from './types';

const metric = (
  key: string,
  label: string,
  value: string,
  helper: string,
  trend: string,
  status: PageMetric['status'],
): PageMetric => ({
  key,
  label,
  value,
  helper,
  trend,
  status,
});

const timeline = [
  {
    time: '2026-04-23 09:15',
    title: '主数据上下文补齐',
    description: '已自动补齐客户、联系人和商机关联锚点。',
    actor: 'Main Agent',
    status: 'success' as const,
  },
  {
    time: '2026-04-23 09:24',
    title: '触发技能编排',
    description: '根据租户策略触发记录系统技能和场景技能组合。',
    actor: 'Scene Orchestrator',
    status: 'processing' as const,
  },
  {
    time: '2026-04-23 09:38',
    title: '等待确认或异步回写',
    description: '进入写回确认或资产沉淀阶段，审计链路完整记录。',
    actor: 'Audit Gate',
    status: 'warning' as const,
  },
];

export const tenantContext: TenantContext = {
  eid: 'eid_yzj_cn_hz_001',
  appId: 'app_ai_crm_prod_01',
  tenantName: '云之家华东样板租户',
  suiteName: 'AI销售助手双系统',
  owner: '张晨路',
  region: '华东 2',
  accessStatus: '接入正常',
  orgSyncStatus: '最近一次全量成功',
  lastSyncAt: '2026-04-23 07:40',
  lastHeartbeatAt: '2026-04-23 11:58',
  seatUsage: '128 / 160',
};

export const dashboardMetrics: PageMetric[] = [
  metric('tenant', '租户接入状态', '12 / 12', '已接入租户', '+2 本周', 'healthy'),
  metric('tool', '动态技能就绪率', '96.4%', '对象技能就绪率', '+1.8%', 'healthy'),
  metric('writeback', '主数据写回成功率', '98.2%', '最近 7 日', '+0.6%', 'healthy'),
  metric('audio', '录音导入完成率', '91.3%', '异步链路完成度', '-1.1%', 'attention'),
  metric('research', '研究快照复用率', '63.8%', '用于拜访材料', '+8.5%', 'healthy'),
  metric('security', '跨租户拦截告警', '3', '近 24 小时', '-4', 'attention'),
];

export const dashboardTrendData: TrendPoint[] = [
  { date: '04-17', writebackSuccess: 96.5, audioCompletion: 87.1, researchReuse: 58.2, visitBriefSuccess: 90.2 },
  { date: '04-18', writebackSuccess: 97.0, audioCompletion: 88.9, researchReuse: 59.4, visitBriefSuccess: 91.8 },
  { date: '04-19', writebackSuccess: 97.4, audioCompletion: 90.1, researchReuse: 61.2, visitBriefSuccess: 92.5 },
  { date: '04-20', writebackSuccess: 97.1, audioCompletion: 89.6, researchReuse: 62.8, visitBriefSuccess: 93.1 },
  { date: '04-21', writebackSuccess: 97.8, audioCompletion: 90.8, researchReuse: 63.4, visitBriefSuccess: 93.6 },
  { date: '04-22', writebackSuccess: 98.0, audioCompletion: 91.0, researchReuse: 63.5, visitBriefSuccess: 94.4 },
  { date: '04-23', writebackSuccess: 98.2, audioCompletion: 91.3, researchReuse: 63.8, visitBriefSuccess: 94.8 },
];

export const rankingData: RankingItem[] = [
  { name: '华东制造事业部', value: 94, category: '拜访材料生成成功率' },
  { name: '汽车零部件样板组', value: 91, category: '录音导入完成率' },
  { name: '新能源 KA 组', value: 89, category: '主数据写回成功率' },
  { name: '渠道拓展团队', value: 84, category: '研究快照复用率' },
  { name: '政企业务组', value: 79, category: '技能确认通过率' },
];

export const systemAlerts: SystemAlert[] = [
  {
    id: 'alert-1',
    title: '录音转写回调延迟升高',
    severity: '高',
    description: '华北节点在过去 30 分钟转写回调平均延迟升至 42s，建议检查语音供应商 SLA。',
    owner: '基础平台组',
    updatedAt: '11:46',
  },
  {
    id: 'alert-2',
    title: '跨租户写回拦截命中',
    severity: '中',
    description: '2 条写回请求携带错误 eid，被审计网关成功阻断，需排查调用方缓存。',
    owner: '安全运营组',
    updatedAt: '10:35',
  },
  {
    id: 'alert-3',
    title: '公司研究来源覆盖不足',
    severity: '中',
    description: '部分医药客户研究仅命中 2 个来源，建议调高外部研究兜底阈值。',
    owner: '研究能力组',
    updatedAt: '09:58',
  },
];

export const systemHealth: SystemHealthItem[] = [
  {
    key: 'orchestrator',
    name: '场景编排服务',
    status: 'healthy',
    value: '99.92%',
    target: '99.5%',
    description: '任务编排与重试正常，队列积压低于阈值。',
  },
  {
    key: 'transcript',
    name: '录音转写链路',
    status: 'attention',
    value: '91.3%',
    target: '95%',
    description: '华北节点存在延迟波动，其他区域稳定。',
  },
  {
    key: 'research',
    name: '外部研究服务',
    status: 'healthy',
    value: '6.4 s',
    target: '< 8 s',
    description: '公司分析快照生成时延控制在目标内。',
  },
  {
    key: 'audit',
    name: '确认审计链路',
    status: 'healthy',
    value: '100%',
    target: '100%',
    description: '所有写回均附带 traceId / taskId / eid / appId。',
  },
];

export const recordPages: Record<string, RecordPageConfig> = {
  customers: {
    key: 'customers',
    title: '客户',
    summary: '正式后台列表页，体现影子系统主数据对象与字段元数据，而不是静态写死 schema 的玩具 CRM。',
    searchPlaceholder: '搜索客户名称 / 行业 / 模板编号',
    metrics: [
      metric('count', '对象总量', '1,284', '影子系统客户对象', '+36', 'healthy'),
      metric('sync', '模板同步成功率', '99.1%', '轻云字段元数据同步', '+0.3%', 'healthy'),
      metric('writeback', '确认写回通过率', '94.8%', '最近 7 日客户写回', '+1.5%', 'healthy'),
    ],
    meta: {
      key: 'customer',
      label: '客户',
      templateId: 'tmpl_customer_01',
      codeId: 'yzj_customer',
      skillVersion: '0.1.0',
      fieldCount: 38,
      generationStatus: '已生成',
      confirmationPolicy: '关键字段二次确认',
      writebackRate: '98.6%',
      writableFields: ['客户名称', '客户等级', '所属行业', '省份', '负责人', '最近拜访时间'],
      readonlyFields: ['templateId', 'codeId', 'eid', 'appId', '创建人'],
    },
    records: [
      {
        id: 'cust-001',
        name: '星海精工股份',
        code: 'CUS-2026-001',
        status: '跟进中',
        owner: '高远',
        industry: '高端装备',
        source: '录音导入',
        updatedAt: '2026-04-23 11:20',
        nextAction: '确认拜访纪要后回写客户标签',
        health: 'healthy',
        tags: ['重点客户', '华东', '录音回写'],
        description: '客户近期关注产线数字化升级，存在多业务线协同机会。',
        related: [
          { label: '最近商机', value: 'AGI 产线升级项目' },
          { label: '客户等级', value: 'A' },
          { label: '最近研究快照', value: '2026-04-22 星海精工研究快照' },
        ],
        timeline,
      },
      {
        id: 'cust-002',
        name: '远澜生物科技',
        code: 'CUS-2026-012',
        status: '待确认',
        owner: '余淼',
        industry: '医药制造',
        source: '公司分析',
        updatedAt: '2026-04-23 10:46',
        nextAction: '补齐采购中心联系人后再触发商机创建',
        health: 'attention',
        tags: ['新客户', '需补齐联系人'],
        description: '研究快照已建立，但联系人与决策链仍不完整。',
        related: [
          { label: '最近任务', value: 'company_research' },
          { label: '联系人数量', value: '2' },
          { label: '待确认字段', value: '采购预算、招标节奏' },
        ],
        timeline,
      },
      {
        id: 'cust-003',
        name: '汇拓能源设备',
        code: 'CUS-2026-018',
        status: '风险关注',
        owner: '宋可欣',
        industry: '新能源装备',
        source: '人工录入',
        updatedAt: '2026-04-22 18:02',
        nextAction: '复核主数据归属，防止跨租户误写',
        health: 'risk',
        tags: ['跨区域', '数据归属待审计'],
        description: '客户曾跨大区流转，主数据归属仍需安全策略确认。',
        related: [
          { label: '审计状态', value: '已拦截 1 次' },
          { label: '负责人', value: '宋可欣' },
          { label: '建议动作', value: '发起管理员复核' },
        ],
        timeline,
      },
    ],
  },
  contacts: {
    key: 'contacts',
    title: '联系人',
    summary: '联系人对象强调角色、影响关系与后续 AI 场景消费，而不是孤立名片列表。',
    searchPlaceholder: '搜索联系人姓名 / 客户 / 角色',
    metrics: [
      metric('count', '对象总量', '3,942', '联系人记录', '+122', 'healthy'),
      metric('relation', '关系边覆盖率', '88.9%', '影响人与决策链', '+4.2%', 'healthy'),
      metric('confirm', '敏感字段确认率', '97.4%', '手机号 / 邮箱确认', '+0.7%', 'healthy'),
    ],
    meta: {
      key: 'contact',
      label: '联系人',
      templateId: 'tmpl_contact_01',
      codeId: 'yzj_contact',
      skillVersion: '0.1.0',
      fieldCount: 31,
      generationStatus: '已生成',
      confirmationPolicy: '手机号与邮箱强确认',
      writebackRate: '97.9%',
      writableFields: ['姓名', '职位', '手机号', '邮箱', '关系标签', '影响力等级'],
      readonlyFields: ['templateId', 'codeId', 'eid', 'appId'],
    },
    records: [
      {
        id: 'cont-001',
        name: '杨嘉禾',
        code: 'CON-2026-101',
        status: '已识别决策人',
        owner: '高远',
        phone: '138****2231',
        customerName: '星海精工股份',
        source: '录音导入',
        updatedAt: '2026-04-23 11:12',
        nextAction: '补充其与生产副总的影响关系',
        health: 'healthy',
        tags: ['采购总监', '关键人'],
        description: '在最近录音中确认其参与年度预算拍板。',
        related: [
          { label: '所属客户', value: '星海精工股份' },
          { label: '影响等级', value: 'A' },
          { label: '最近场景', value: '录音导入与拜访分析' },
        ],
        timeline,
      },
      {
        id: 'cont-002',
        name: '何雨潼',
        code: 'CON-2026-122',
        status: '待补齐',
        owner: '余淼',
        phone: '156****9021',
        customerName: '远澜生物科技',
        source: '公司分析',
        updatedAt: '2026-04-23 09:44',
        nextAction: '确认邮箱后触发拜访材料更新',
        health: 'attention',
        tags: ['研究提取', '邮箱缺失'],
        description: '来自公开资料与销售旧记录拼合，仍需人工确认。',
        related: [
          { label: '职位', value: '信息化负责人' },
          { label: '来源', value: '公司分析快照' },
          { label: '确认策略', value: '人工确认' },
        ],
        timeline,
      },
    ],
  },
  opportunities: {
    key: 'opportunities',
    title: '商机',
    summary: '商机页聚焦阶段推进、金额、风险与写回链路，是 AI 场景任务的重要锚点。',
    searchPlaceholder: '搜索商机名称 / 客户 / 阶段',
    metrics: [
      metric('count', '对象总量', '486', '在管商机', '+14', 'healthy'),
      metric('stage', '阶段识别准确率', '92.1%', '由录音与跟进归纳', '+2.1%', 'healthy'),
      metric('risk', '风险商机占比', '13.4%', '需经理复核', '-1.8%', 'attention'),
    ],
    meta: {
      key: 'opportunity',
      label: '商机',
      templateId: 'tmpl_oppty_01',
      codeId: 'yzj_opportunity',
      skillVersion: '0.1.0',
      fieldCount: 44,
      generationStatus: '已生成',
      confirmationPolicy: '金额与阶段强确认',
      writebackRate: '96.3%',
      writableFields: ['商机名称', '阶段', '预计金额', '预计关闭时间', '负责人', '风险等级'],
      readonlyFields: ['templateId', 'codeId', 'eid', 'appId', '创建来源'],
    },
    records: [
      {
        id: 'opp-001',
        name: 'AGI 产线升级项目',
        code: 'OPP-2026-009',
        status: '方案评估',
        owner: '高远',
        amount: '¥ 280 万',
        customerName: '星海精工股份',
        source: '录音导入',
        updatedAt: '2026-04-23 11:28',
        nextAction: '生成拜访材料并同步关键风险',
        health: 'healthy',
        tags: ['重点商机', '方案评估'],
        description: '项目已进入联合评估阶段，需准备 ROI 与落地节奏。',
        related: [
          { label: '客户', value: '星海精工股份' },
          { label: '预计关闭', value: '2026-06-30' },
          { label: '最近跟进', value: '2026-04-23 商机跟进记录' },
        ],
        timeline,
      },
      {
        id: 'opp-002',
        name: 'MES 一体化替换',
        code: 'OPP-2026-031',
        status: '待创建',
        owner: '余淼',
        amount: '¥ 90 万',
        customerName: '远澜生物科技',
        source: '公司分析',
        updatedAt: '2026-04-23 10:20',
        nextAction: '客户存在、联系人不足，需先补齐后建商机',
        health: 'attention',
        tags: ['研究导出', '商机待补齐'],
        description: '公司分析识别到项目机会，但主数据上下文尚未闭环。',
        related: [
          { label: '创建条件', value: '需至少 1 个关键联系人' },
          { label: '研究结论', value: '存在预算窗口' },
          { label: '当前状态', value: '草稿' },
        ],
        timeline,
      },
    ],
  },
  followups: {
    key: 'followups',
    title: '商机跟进记录',
    summary: '跟进记录页明确承接录音导入与拜访分析结果，是最关键的 AI 写回结果查看位。',
    searchPlaceholder: '搜索跟进摘要 / 客户 / 商机',
    metrics: [
      metric('count', '对象总量', '2,318', '跟进记录', '+68', 'healthy'),
      metric('audio', '录音入库占比', '54.6%', '来源于录音导入', '+6.3%', 'healthy'),
      metric('confirm', '回写待确认', '37', '高风险写回需确认', '-5', 'attention'),
    ],
    meta: {
      key: 'followup',
      label: '商机跟进记录',
      templateId: 'tmpl_followup_01',
      codeId: 'yzj_followup',
      skillVersion: '0.1.0',
      fieldCount: 52,
      generationStatus: '已生成',
      confirmationPolicy: '摘要、结论、下一步动作确认',
      writebackRate: '95.4%',
      writableFields: ['拜访摘要', '关键结论', '风险提示', '下一步动作', '录音资产关联'],
      readonlyFields: ['templateId', 'codeId', 'eid', 'appId', 'traceId'],
    },
    records: [
      {
        id: 'follow-001',
        name: '星海精工 4 月生产数字化拜访',
        code: 'FUP-2026-301',
        status: '已回写',
        owner: '高远',
        customerName: '星海精工股份',
        opportunityName: 'AGI 产线升级项目',
        source: '录音导入',
        updatedAt: '2026-04-23 11:31',
        nextAction: '确认报价材料与内部方案会',
        health: 'healthy',
        tags: ['录音分析', '已回写'],
        description: '已按先补齐上下文、再建跟进记录、最后异步分析的时序完成回写。',
        related: [
          { label: 'traceId', value: 'trace-20260423-001' },
          { label: 'taskId', value: 'task-audio-009' },
          { label: '录音时长', value: '36 分钟' },
        ],
        timeline,
      },
      {
        id: 'follow-002',
        name: '远澜生物调研会记录',
        code: 'FUP-2026-319',
        status: '待确认',
        owner: '余淼',
        customerName: '远澜生物科技',
        opportunityName: 'MES 一体化替换',
        source: '人工补录',
        updatedAt: '2026-04-23 10:48',
        nextAction: '确认商机金额和推进阶段后再回写',
        health: 'attention',
        tags: ['待确认', '金额风险'],
        description: 'AI 已生成摘要和建议动作，但金额字段置信度不足。',
        related: [
          { label: '建议动作', value: '补齐采购节奏' },
          { label: '确认策略', value: '销售经理确认' },
          { label: '风险', value: '金额字段低置信度' },
        ],
        timeline,
      },
    ],
  },
};

export const assetPages: Record<string, AssetPageConfig> = {
  sessions: {
    key: 'sessions',
    title: '会话任务',
    summary: '用于查看用户 AI 端会话、任务推进与实体锚点映射，是管理员观察真实使用链路的核心入口。',
    metrics: [
      metric('session', '活跃会话', '84', '近 24 小时', '+12', 'healthy'),
      metric('task', '任务完成率', '89.6%', '场景任务闭环', '+3.1%', 'healthy'),
      metric('manual', '人工接管', '6.2%', '需要运营协助', '-0.4%', 'attention'),
    ],
    items: [
      {
        id: 'sess-001',
        title: '星海精工 录音导入链路',
        status: '运行中',
        owner: '高远',
        entityAnchor: '客户/星海精工股份',
        summary: '用户从 AI 端发起录音导入，已补齐客户与商机并创建跟进记录。',
        updatedAt: '2026-04-23 11:33',
        score: '92 / 100',
        tags: ['audio-import', 'writeback'],
        timeline,
      },
      {
        id: 'sess-002',
        title: '远澜生物 准备拜访材料',
        status: '待确认',
        owner: '余淼',
        entityAnchor: '客户/远澜生物科技',
        summary: '系统已组合主数据与研究快照，等待销售确认拜访问题清单。',
        updatedAt: '2026-04-23 10:52',
        score: '87 / 100',
        tags: ['visit-prepare', 'research'],
        timeline,
      },
    ],
  },
  'audio-analysis': {
    key: 'audio-analysis',
    title: '录音分析资产',
    summary: '统一查看录音、转写、异步分析、跟进记录回写的全链路资产状态。',
    metrics: [
      metric('asset', '录音资产', '362', '已归档录音', '+28', 'healthy'),
      metric('transcript', '转写成功率', '94.2%', '最近 7 日', '-0.8%', 'attention'),
      metric('latency', '平均完成时长', '12.4 分钟', '从上传到分析完成', '+0.6 分钟', 'attention'),
    ],
    items: [
      {
        id: 'audio-001',
        title: '星海精工 4/23 拜访录音',
        status: '分析完成',
        owner: '高远',
        entityAnchor: '商机/AGI 产线升级项目',
        summary: '已生成跟进摘要、问题清单与风险提示，并绑定至跟进记录。',
        updatedAt: '2026-04-23 11:32',
        score: '36 分钟',
        tags: ['已回写', '会议室录音'],
        timeline,
      },
      {
        id: 'audio-002',
        title: '远澜生物 需求沟通录音',
        status: '等待确认',
        owner: '余淼',
        entityAnchor: '客户/远澜生物科技',
        summary: '客户已匹配成功，但商机金额和阶段仍待确认后回写。',
        updatedAt: '2026-04-23 10:58',
        score: '18 分钟',
        tags: ['金额待确认', '研究补齐'],
        timeline,
      },
    ],
  },
  'research-snapshots': {
    key: 'research-snapshots',
    title: '公司研究快照',
    summary: '研究快照按外部技能资产管理，支持拜访材料、风险分析与任务回看复用。',
    metrics: [
      metric('snapshot', '研究快照', '516', '已沉淀研究资产', '+21', 'healthy'),
      metric('reuse', '复用率', '63.8%', '被下游消费', '+8.5%', 'healthy'),
      metric('freshness', '新鲜度达标', '82.4%', '7 日内更新', '+2.6%', 'healthy'),
    ],
    items: [
      {
        id: 'research-001',
        title: '星海精工 行业与财报快照',
        status: '可复用',
        owner: '研究能力组',
        entityAnchor: '客户/星海精工股份',
        summary: '聚焦产线升级预算、产能扩张计划与竞对动向。',
        updatedAt: '2026-04-22 18:44',
        score: '6 个来源',
        tags: ['财报', '行业资讯'],
        timeline,
      },
      {
        id: 'research-002',
        title: '远澜生物 医药数字化快照',
        status: '待补源',
        owner: '研究能力组',
        entityAnchor: '客户/远澜生物科技',
        summary: '已有招采与行业信息，但缺少近半年舆情和 IT 负责人动态。',
        updatedAt: '2026-04-23 09:16',
        score: '2 个来源',
        tags: ['来源不足', '需扩展'],
        timeline,
      },
    ],
  },
  'visit-briefs': {
    key: 'visit-briefs',
    title: '拜访材料结果',
    summary: '输出拜访摘要卡、问题清单、风险提示与建议动作，服务于销售临门一脚准备。',
    metrics: [
      metric('brief', '拜访材料', '244', '已生成结果', '+19', 'healthy'),
      metric('success', '生成成功率', '94.8%', '最近 7 日', '+2.4%', 'healthy'),
      metric('quality', '人工采纳率', '78.6%', '销售实际采用', '+6.1%', 'healthy'),
    ],
    items: [
      {
        id: 'brief-001',
        title: '星海精工 联合评审拜访包',
        status: '已下发',
        owner: '高远',
        entityAnchor: '客户/星海精工股份',
        summary: '已组合主数据、研究快照、录音分析与 AI 记忆，生成正式拜访提纲。',
        updatedAt: '2026-04-23 11:40',
        score: 'A 级',
        tags: ['主数据+研究+录音'],
        timeline,
      },
      {
        id: 'brief-002',
        title: '远澜生物 初访准备包',
        status: '草稿',
        owner: '余淼',
        entityAnchor: '客户/远澜生物科技',
        summary: '当前仅使用主数据与研究快照，待补齐录音分析后提升完整度。',
        updatedAt: '2026-04-23 10:51',
        score: 'B+',
        tags: ['主数据+研究'],
        timeline,
      },
    ],
  },
};

export const toolRegistryRows: ToolRegistryItem[] = [
  {
    id: 'tool-001',
    objectKey: 'customer',
    label: '客户对象技能',
    templateId: 'tmpl_customer_01',
    codeId: 'yzj_customer',
    generationStatus: '已生成',
    writableFields: ['客户名称', '客户等级', '所属行业', '省份', '负责人'],
    readonlyFields: ['eid', 'appId', 'templateId'],
    confirmationPolicy: '关键字段二次确认',
    version: '0.1.0',
    updatedAt: '2026-04-23 08:12',
  },
  {
    id: 'tool-002',
    objectKey: 'followup',
    label: '商机跟进记录技能',
    templateId: 'tmpl_followup_01',
    codeId: 'yzj_followup',
    generationStatus: '已生成',
    writableFields: ['拜访摘要', '关键结论', '风险提示', '下一步动作'],
    readonlyFields: ['traceId', 'taskId', 'eid', 'appId'],
    confirmationPolicy: '摘要与结论确认',
    version: '0.1.0',
    updatedAt: '2026-04-23 09:05',
  },
];

export const sceneSkillRows: SkillCatalogItem[] = [
  {
    id: 'scene-001',
    label: '录音导入与拜访分析',
    type: '场景技能',
    trigger: '上传录音 / 口述导入',
    route: '/chat/audio-import',
    dependencies: ['客户技能', '商机技能', '跟进记录技能', '转写服务'],
    status: '运行中',
    owner: '场景编排组',
    sla: 'P95 < 15 分钟',
  },
  {
    id: 'scene-002',
    label: '准备拜访材料',
    type: '场景技能',
    trigger: '自然语言请求 / 快捷入口',
    route: '/chat/visit-prepare',
    dependencies: ['研究快照', '录音分析资产', '主数据对象'],
    status: '运行中',
    owner: '场景编排组',
    sla: 'P95 < 8 秒',
  },
];

export const externalSkillRows: SkillCatalogItem[] = [
  {
    id: 'ext-001',
    label: '公司分析',
    type: '外部技能',
    trigger: '公司名称 / 客户研究',
    route: '/chat/company-research',
    dependencies: ['研究服务 Provider', '来源解析', '快照沉淀'],
    status: '运行中',
    owner: '研究能力组',
    sla: 'P95 < 10 秒',
  },
  {
    id: 'ext-002',
    label: '录音转写',
    type: '外部技能',
    trigger: '音频文件导入',
    route: '/chat/audio-import',
    dependencies: ['语音服务 Provider', '对象存储'],
    status: '告警中',
    owner: '语音能力组',
    sla: 'P95 < 5 分钟',
  },
];

export const writebackPolicies: WritebackPolicy[] = [
  {
    id: 'policy-001',
    objectKey: 'customer',
    strategy: '关键字段二次确认',
    trigger: '新增客户 / 修改等级 / 修改归属',
    approver: '销售经理',
    auditSampling: '100%',
    rollbackRule: '回滚至最近一次人工确认快照',
    updatedAt: '2026-04-22 15:20',
  },
  {
    id: 'policy-002',
    objectKey: 'followup',
    strategy: '摘要与建议动作确认',
    trigger: '录音导入生成跟进记录',
    approver: '销售本人',
    auditSampling: '30%',
    rollbackRule: '保留 trace 对应草稿版本',
    updatedAt: '2026-04-23 08:46',
  },
];

export const traceLogs: TraceLog[] = [
  {
    traceId: 'trace-20260423-001',
    taskId: 'task-audio-009',
    eid: tenantContext.eid,
    appId: tenantContext.appId,
    scene: 'scene.audio_import',
    status: '成功',
    toolChain: ['shadow.customer.query', 'shadow.opportunity.query', 'shadow.followup.create', 'ext.audio.transcript'],
    writebackResult: '商机跟进记录回写成功',
    timestamp: '2026-04-23 11:32:14',
  },
  {
    traceId: 'trace-20260423-017',
    taskId: 'task-research-013',
    eid: tenantContext.eid,
    appId: tenantContext.appId,
    scene: 'ext.company_research',
    status: '待补源',
    toolChain: ['ext.research.search', 'ext.research.extract', 'asset.research.snapshot.upsert'],
    writebackResult: '研究快照已生成，未触发主数据写回',
    timestamp: '2026-04-23 09:18:22',
  },
  {
    traceId: 'trace-20260423-021',
    taskId: 'task-visit-004',
    eid: tenantContext.eid,
    appId: tenantContext.appId,
    scene: 'scene.visit_prepare',
    status: '成功',
    toolChain: ['shadow.customer.query', 'asset.research.snapshot.query', 'asset.audio.analysis.query', 'scene.visit_prepare.render'],
    writebackResult: '拜访材料结果落盘成功',
    timestamp: '2026-04-23 10:51:03',
  },
];

export const settingPages: Record<string, SettingPageConfig> = {
  'tenant-app': {
    key: 'tenant-app',
    title: '租户 / 应用识别',
    summary: '维护租户、应用实例、访问域和环境隔离，是双系统共享上下文的起点。',
    metrics: [
      metric('eid', '租户识别', tenantContext.eid, '当前活动租户', '稳定', 'healthy'),
      metric('app', '应用实例', tenantContext.appId, '当前活动应用', '稳定', 'healthy'),
    ],
    groups: [
      {
        key: 'tenant',
        title: '基础识别',
        summary: '定义管理员后台和用户 AI 端共享的租户上下文。',
        tags: ['eid', 'appId', 'environment'],
        healthNote: '当前双系统均已绑定同一业务域上下文。',
        fields: [
          { name: 'tenantName', label: '租户名称', value: tenantContext.tenantName, kind: 'text' },
          { name: 'suiteName', label: '套件名称', value: tenantContext.suiteName, kind: 'text' },
          { name: 'eid', label: 'eid', value: tenantContext.eid, kind: 'text' },
          { name: 'appId', label: 'appId', value: tenantContext.appId, kind: 'text' },
          { name: 'region', label: '部署区域', value: tenantContext.region, kind: 'select', options: ['华东 2', '华南 1', '华北 1'] },
        ],
      },
      {
        key: 'access',
        title: '访问约束',
        summary: '控制回调域、单点入口和租户隔离策略。',
        tags: ['domain', 'callback', 'isolation'],
        healthNote: '跨租户拦截已启用，审计链路完整。',
        fields: [
          { name: 'adminDomain', label: '后台域名', value: 'https://admin.ai-crm.yzj.mock', kind: 'text' },
          { name: 'assistantDomain', label: 'AI 端域名', value: 'https://assistant.ai-crm.yzj.mock', kind: 'text' },
          { name: 'enforceIsolation', label: '强制租户隔离', value: true, kind: 'switch' },
        ],
      },
    ],
  },
  'yzj-auth': {
    key: 'yzj-auth',
    title: '云之家接入',
    summary: '配置 OAuth、服务端签名与轻云权限，是系统接入的基础能力。',
    metrics: [
      metric('oauth', 'OAuth 状态', '已连接', '最近心跳正常', '稳定', 'healthy'),
      metric('sign', '签名校验', '100%', '最近 24 小时', '稳定', 'healthy'),
    ],
    groups: [
      {
        key: 'oauth',
        title: 'OAuth 与应用凭证',
        summary: '维护回调地址、客户端凭证与票据刷新策略。',
        tags: ['oauth', 'token'],
        healthNote: '票据刷新成功率 100%。',
        fields: [
          { name: 'clientId', label: 'Client ID', value: 'yzj-demo-client-id', kind: 'text' },
          { name: 'redirect', label: '回调地址', value: 'https://admin.ai-crm.yzj.mock/oauth/callback', kind: 'text' },
          { name: 'tokenRefresh', label: '自动刷新 Token', value: true, kind: 'switch' },
        ],
      },
      {
        key: 'lightcloud',
        title: '轻云权限范围',
        summary: '控制记录系统对象的读写权限。',
        tags: ['lightcloud', 'permission'],
        healthNote: '客户、联系人、商机、跟进记录权限均已授予。',
        fields: [
          { name: 'scopes', label: '授权范围', value: 'customer, contact, opportunity, followup', kind: 'textarea' },
          { name: 'signatureMode', label: '签名模式', value: 'HMAC-SHA256', kind: 'select', options: ['HMAC-SHA256', 'RSA'] },
        ],
      },
    ],
  },
  'org-sync': {
    key: 'org-sync',
    title: '组织同步',
    summary: '同步部门、成员、岗位与汇报关系，为联系人归属和权限判断提供基础。',
    metrics: [
      metric('full', '全量同步', '每日 01:00', '最近一次成功', '稳定', 'healthy'),
      metric('delta', '增量延迟', '4 分钟', '最近 24 小时', '+1 分钟', 'healthy'),
    ],
    groups: [
      {
        key: 'sync',
        title: '同步调度',
        summary: '全量 + 增量双模式运行。',
        tags: ['full', 'delta'],
        healthNote: '组织树未发现断链。',
        fields: [
          { name: 'fullSync', label: '全量同步 Cron', value: '每日 01:00', kind: 'text' },
          { name: 'deltaSync', label: '增量同步间隔', value: '5 分钟', kind: 'select', options: ['5 分钟', '10 分钟', '15 分钟'] },
          { name: 'syncManager', label: '同步负责人', value: '基础平台组', kind: 'text' },
        ],
      },
    ],
  },
  models: {
    key: 'models',
    title: '模型 / 转写 / 研究 / 存储',
    summary: '统一管理主模型、转写、研究 Provider 与资产存储策略。',
    metrics: [
      metric('model', '主模型可用性', '99.5%', '最近 7 日', '+0.2%', 'healthy'),
      metric('storage', '对象存储可用性', '99.99%', '最近 30 日', '稳定', 'healthy'),
    ],
    groups: [
      {
        key: 'model',
        title: '主模型',
        summary: '负责 AI 对话、任务编排与拜访材料生成。',
        tags: ['llm', 'reasoning'],
        healthNote: '主模型和回退模型均可用。',
        fields: [
          { name: 'primaryModel', label: '主模型', value: 'glm-4.5-flash / mock', kind: 'text' },
          { name: 'fallbackModel', label: '回退模型', value: 'qwen-plus / mock', kind: 'text' },
          { name: 'enableThought', label: '启用思考输出', value: true, kind: 'switch' },
        ],
      },
      {
        key: 'audio',
        title: '录音转写',
        summary: '负责音频识别与段落切分。',
        tags: ['audio', 'transcript'],
        healthNote: '华北节点延迟偏高，其他节点正常。',
        fields: [
          { name: 'transcriptProvider', label: '转写 Provider', value: 'tongyi-agent / mock', kind: 'text' },
          { name: 'maxDuration', label: '单文件时长上限', value: '90 分钟', kind: 'select', options: ['60 分钟', '90 分钟', '120 分钟'] },
        ],
      },
      {
        key: 'research',
        title: '公司研究',
        summary: '负责外部检索与研究快照沉淀。',
        tags: ['research', 'snapshot'],
        healthNote: '医药行业来源覆盖需增强。',
        fields: [
          { name: 'searchDepth', label: '默认检索深度', value: '标准', kind: 'select', options: ['标准', '增强'] },
          { name: 'snapshotTtl', label: '快照有效期', value: '7 天', kind: 'select', options: ['3 天', '7 天', '14 天'] },
        ],
      },
    ],
  },
  observability: {
    key: 'observability',
    title: '可观测性',
    summary: '聚焦 traceId / taskId / eid / appId、tool 调用链与写回结果，支持管理员定位场景问题。',
    metrics: [
      metric('trace', 'Trace 完整率', '100%', '所有任务均带上下文', '稳定', 'healthy'),
      metric('audit', '写回审计覆盖率', '100%', '高风险操作全量记录', '稳定', 'healthy'),
    ],
    groups: [
      {
        key: 'trace',
        title: '追踪上下文',
        summary: '统一记录 traceId / taskId / eid / appId。',
        tags: ['traceId', 'taskId', 'eid', 'appId'],
        healthNote: '当前所有链路均可追踪到上下文。',
        fields: [
          { name: 'traceExport', label: 'Trace 导出', value: 'OpenTelemetry / mock', kind: 'text' },
          { name: 'traceRetention', label: '保留周期', value: '90 天', kind: 'select', options: ['30 天', '90 天', '180 天'] },
          { name: 'enableAudit', label: '启用写回审计', value: true, kind: 'switch' },
        ],
      },
    ],
  },
  security: {
    key: 'security',
    title: '安全与运营',
    summary: '覆盖跨租户拦截、字段脱敏、人工接管和异常处理策略。',
    metrics: [
      metric('block', '跨租户拦截', '100%', '应拦截请求全部阻断', '稳定', 'healthy'),
      metric('mask', '敏感字段脱敏', '100%', '手机号 / 邮箱等', '稳定', 'healthy'),
    ],
    groups: [
      {
        key: 'security',
        title: '风险控制',
        summary: '保障正式后台和 AI 端的共享数据安全。',
        tags: ['masking', 'handoff', 'audit'],
        healthNote: '未发生高危越权事件。',
        fields: [
          { name: 'crossTenantBlock', label: '跨租户写回拦截', value: true, kind: 'switch' },
          { name: 'manualHandoff', label: '人工接管开关', value: true, kind: 'switch' },
          { name: 'piiMasking', label: 'PII 脱敏规则', value: '手机号 / 邮箱 / 身份标识', kind: 'textarea' },
        ],
      },
    ],
  },
};

export const conversationSessions: ConversationSession[] = [
  {
    key: 'conv-001',
    label: '星海精工录音导入',
    route: '/chat/audio-import',
    group: '今天',
    lastMessage: '先补齐客户和商机，再创建跟进记录。',
    updatedAt: '11:31',
    badgeCount: 1,
    scene: 'audio-import',
  },
  {
    key: 'conv-002',
    label: '远澜生物拜访准备',
    route: '/chat/visit-prepare',
    group: '今天',
    lastMessage: '已组合主数据和研究快照，等待你确认问题清单。',
    updatedAt: '10:52',
    scene: 'visit-prepare',
  },
  {
    key: 'conv-003',
    label: '公司分析模板',
    route: '/chat/company-research',
    group: '昨天',
    lastMessage: '当前作为外部研究能力入口，不直接写主数据。',
    updatedAt: '昨天',
    scene: 'company-research',
  },
];

export const sceneTasks: SceneTask[] = [
  {
    id: 'task-audio-009',
    title: '星海精工录音导入',
    scene: '录音导入与拜访分析',
    route: '/chat/audio-import',
    status: '运行中',
    progress: 82,
    owner: '高远',
    entityAnchor: '商机/AGI 产线升级项目',
    nextAction: '确认异步分析摘要并完成回写',
    traceId: 'trace-20260423-001',
    taskId: 'task-audio-009',
    eid: tenantContext.eid,
    appId: tenantContext.appId,
    updatedAt: '11:32',
  },
  {
    id: 'task-research-013',
    title: '远澜生物公司分析',
    scene: '公司分析',
    route: '/chat/company-research',
    status: '待补源',
    progress: 64,
    owner: '余淼',
    entityAnchor: '客户/远澜生物科技',
    nextAction: '增加两个行业来源后更新快照',
    traceId: 'trace-20260423-017',
    taskId: 'task-research-013',
    eid: tenantContext.eid,
    appId: tenantContext.appId,
    updatedAt: '09:18',
  },
  {
    id: 'task-visit-004',
    title: '星海精工准备拜访材料',
    scene: '准备拜访材料',
    route: '/chat/visit-prepare',
    status: '已完成',
    progress: 100,
    owner: '高远',
    entityAnchor: '客户/星海精工股份',
    nextAction: '下发材料并跟踪采纳情况',
    traceId: 'trace-20260423-021',
    taskId: 'task-visit-004',
    eid: tenantContext.eid,
    appId: tenantContext.appId,
    updatedAt: '10:51',
  },
];

export const researchSnapshots: ResearchSnapshot[] = [
  {
    id: 'snap-001',
    companyName: '星海精工股份',
    intent: '准备联合评审拜访',
    sourceCount: 6,
    freshness: '1 天内',
    owner: '研究能力组',
    updatedAt: '2026-04-22 18:44',
    summary: '公司正推进产线升级和海外交付体系重构，预算窗口明确，重点关注 ROI 和交付周期。',
    citations: [
      { title: '2025 年年报摘要', source: '企业公开披露' },
      { title: '行业协会产线升级观察', source: '行业报告' },
      { title: '最近 30 天新闻提及', source: '媒体聚合' },
    ],
    risks: ['采购流程跨部门审批较长', '竞争对手已提前进场'],
    opportunities: ['预算已列入 CAPEX', '工厂数字化 KPI 明确'],
  },
  {
    id: 'snap-002',
    companyName: '远澜生物科技',
    intent: '补充初访背景',
    sourceCount: 2,
    freshness: '4 小时内',
    owner: '研究能力组',
    updatedAt: '2026-04-23 09:16',
    summary: '公司具备数字化改造意愿，但采购链与 IT 负责人公开信息有限。',
    citations: [
      { title: '行业资讯摘录', source: '公开资讯' },
      { title: '企业官网公告', source: '企业官网' },
    ],
    risks: ['来源数量不足', '关键信息需人工核实'],
    opportunities: ['信息化改造正在预算讨论期'],
  },
];

export const audioImportTasks: AudioImportTask[] = [
  {
    id: 'audio-task-001',
    title: '星海精工 4/23 拜访录音',
    branch: '有客户有商机',
    customerName: '星海精工股份',
    opportunityName: 'AGI 产线升级项目',
    duration: '36 分钟',
    transcriptStatus: '已转写',
    analysisStatus: '已分析',
    writebackStatus: '已回写',
    progress: 100,
    owner: '高远',
    updatedAt: '11:32',
    steps: [
      { title: '校验客户上下文', status: 'completed', description: '命中客户与关键联系人。' },
      { title: '校验商机上下文', status: 'completed', description: '命中商机并识别当前阶段。' },
      { title: '创建跟进记录草稿', status: 'completed', description: '先建记录，再进入异步分析。' },
      { title: '异步分析录音', status: 'completed', description: '生成摘要、风险与建议动作。' },
    ],
  },
  {
    id: 'audio-task-002',
    title: '远澜生物 需求沟通录音',
    branch: '有客户无商机',
    customerName: '远澜生物科技',
    duration: '18 分钟',
    transcriptStatus: '已转写',
    analysisStatus: '分析中',
    writebackStatus: '待确认',
    progress: 72,
    owner: '余淼',
    updatedAt: '10:58',
    steps: [
      { title: '校验客户上下文', status: 'completed', description: '客户已存在。' },
      { title: '校验商机上下文', status: 'warning', description: '未命中商机，需先补齐。' },
      { title: '创建跟进记录草稿', status: 'completed', description: '已先建跟进记录草稿。' },
      { title: '异步分析录音', status: 'running', description: '等待金额与阶段确认。' },
    ],
  },
  {
    id: 'audio-task-003',
    title: '渠道拓展陌生拜访录音',
    branch: '无客户无商机',
    duration: '12 分钟',
    transcriptStatus: '已转写',
    analysisStatus: '待补齐上下文',
    writebackStatus: '未开始',
    progress: 34,
    owner: '赵天一',
    updatedAt: '09:42',
    steps: [
      { title: '校验客户上下文', status: 'warning', description: '客户不存在，需先创建。' },
      { title: '校验商机上下文', status: 'draft', description: '需客户存在后才能建商机。' },
      { title: '创建跟进记录草稿', status: 'draft', description: '等待上下文补齐。' },
      { title: '异步分析录音', status: 'draft', description: '未进入分析阶段。' },
    ],
  },
];

export const visitBriefs: VisitBrief[] = [
  {
    id: 'brief-view-001',
    customerName: '星海精工股份',
    theme: '联合评审会前准备',
    owner: '高远',
    updatedAt: '2026-04-23 11:40',
    sourceMix: ['主数据', '公司研究快照', '录音分析', 'AI 记忆'],
    summary: [
      '客户预算已在本季度 CAPEX 中明确，决策链以采购总监和生产副总为核心。',
      '最近录音确认客户关心交付周期、ROI 和对现有 MES 的迁移风险。',
    ],
    questions: [
      '客户最担心的停产窗口具体是几天？',
      '采购部与生产部谁拥有最终项目拍板权？',
      '是否需要提供分阶段上线方案与回滚计划？',
    ],
    risks: [
      '竞争对手已先行提供初步报价。',
      'IT 与生产部门目标不完全一致。',
    ],
    actions: ['准备 ROI 对比表', '准备分阶段上线计划', '会后 24 小时内形成确认纪要'],
  },
  {
    id: 'brief-view-002',
    customerName: '远澜生物科技',
    theme: '初访准备',
    owner: '余淼',
    updatedAt: '2026-04-23 10:51',
    sourceMix: ['主数据', '公司研究快照'],
    summary: ['已知客户对数字化改造有兴趣，但关键联系人和预算信息仍不足。'],
    questions: ['此次拜访是否以信息化调研为主，还是已有明确项目？', '预算讨论周期是否在本季度？'],
    risks: ['公开来源不足，需注意信息过度推断。'],
    actions: ['优先确认联系人地图', '获取项目背景材料'],
  },
];

export const assistantScenes: Record<string, AssistantScene> = {
  chat: {
    key: 'chat',
    route: '/chat',
    title: 'AI 销售工作台',
    subtitle: '自然语言驱动主入口',
    headline: '让销售从对话开始，而不是从表格开始。',
    description: '在这里直接发起客户录入、查询、录音导入、公司分析和拜访准备，系统会自动调度场景技能、记录系统技能与外部技能。',
    defaultInput: '帮我查看星海精工最近的商机和跟进情况。',
    prompts: [
      { key: 'p1', label: '录入客户 / 联系人 / 商机 / 跟进', description: '命中记录系统技能并进入确认写回。' },
      { key: 'p2', label: '查询客户 / 商机 / 跟进', description: '返回结构化结果并可跳转记录系统。' },
      { key: 'p3', label: '导入录音并生成跟进记录', description: '先补齐上下文，再异步分析录音。' },
      { key: 'p4', label: '分析公司', description: '按外部研究能力生成快照。' },
      { key: 'p5', label: '准备拜访材料', description: '组合主数据、研究、录音和 AI 记忆输出。' },
    ],
    hotTopics: [
      { key: 'h1', title: '今天有哪些重点客户待跟进？', description: '结合任务和主数据快速盘点。' },
      { key: 'h2', title: '上传录音后会先做什么？', description: '按正式时序先补齐上下文，再建跟进记录。' },
      { key: 'h3', title: '公司分析怎么被拜访材料复用？', description: '研究快照会作为多源输入之一。' },
    ],
    guides: [
      { key: 'g1', title: '先对话后结构化', description: '销售先说需求，系统再调技能和对象。' },
      { key: 'g2', title: '确认后再写回', description: '关键字段写回前保留确认环节和审计。' },
      { key: 'g3', title: '双系统共用上下文', description: '管理员后台和用户端共用同一租户与任务资产。' },
    ],
    taskCards: [
      { key: 't1', title: '运行中任务', status: '3 个', description: '录音分析、公司研究、拜访准备并行推进。', metric: '平均完成 84%' },
      { key: 't2', title: '待确认写回', status: '5 个', description: '集中在金额、阶段和关键摘要。', metric: '2 个高优先级' },
      { key: 't3', title: '可复用资产', status: '18 个', description: '研究快照和录音分析结果可直接复用。', metric: '今日新增 6 个' },
    ],
  },
  'audio-import': {
    key: 'audio-import',
    route: '/chat/audio-import',
    title: '录音导入与拜访分析',
    subtitle: '先补齐上下文，再建跟进记录，再异步分析',
    headline: '录音不是直接出总结，而是进入正式业务链路。',
    description: '页面明确展示三类上下文分支：无客户无商机、有客户无商机、有客户有商机，并把创建跟进记录放在异步分析之前。',
    defaultInput: '上传这段录音，帮我按正式流程生成跟进记录。',
    prompts: [
      { key: 'a1', label: '无客户无商机', description: '先创建客户，再补商机，再进分析。' },
      { key: 'a2', label: '有客户无商机', description: '先补商机，再创建跟进记录。' },
      { key: 'a3', label: '有客户有商机', description: '直接建立跟进记录草稿后异步分析。' },
    ],
    hotTopics: [
      { key: 'ah1', title: '怎么保证不是先出报告？', description: '因为跟进记录是正式写回锚点。' },
      { key: 'ah2', title: '录音异常怎么处理？', description: '转写超时、金额低置信度会进入待确认。' },
    ],
    guides: [
      { key: 'ag1', title: '三段式时序', description: '上下文校验 -> 跟进记录草稿 -> 异步分析。' },
      { key: 'ag2', title: '审计不丢', description: 'traceId / taskId 全程贯穿。' },
    ],
    taskCards: [
      { key: 'at1', title: '上下文分支', status: '3 类', description: '确保不同场景不被误处理。', metric: '100% 命中规则' },
      { key: 'at2', title: '转写回调', status: '91.3%', description: '当前完成率略有波动。', metric: 'P95 12.4 分钟' },
    ],
  },
  'company-research': {
    key: 'company-research',
    route: '/chat/company-research',
    title: '公司分析',
    subtitle: '外部研究能力入口',
    headline: '先作为外部技能接入，后续再演进为深度分析中心。',
    description: '当前语义强调公司分析是外部研究能力，不直接越过确认回写主数据，而是先形成研究快照资产。',
    defaultInput: '帮我分析远澜生物科技，输出研究快照。',
    prompts: [
      { key: 'r1', label: '生成研究快照', description: '输出来源、摘要、机会和风险。' },
      { key: 'r2', label: '补充来源', description: '当来源数不足时触发兜底。' },
      { key: 'r3', label: '引用到拜访材料', description: '把研究快照作为拜访准备输入。' },
    ],
    hotTopics: [
      { key: 'rh1', title: '研究快照会写回客户吗？', description: '不会直接写客户主数据。' },
      { key: 'rh2', title: '来源不足怎么办？', description: '会先标记待补源，而不是假装完整。' },
    ],
    guides: [
      { key: 'rg1', title: '外部技能资产化', description: '研究结果先沉淀成可复用快照。' },
      { key: 'rg2', title: '来源透明', description: '所有分析都带引用来源和更新时间。' },
    ],
    taskCards: [
      { key: 'rt1', title: '研究快照', status: '516 个', description: '可被拜访材料与风险分析复用。', metric: '63.8% 复用率' },
      { key: 'rt2', title: '来源覆盖', status: '82.4%', description: '7 日内新鲜度达标。', metric: '医药行业待增强' },
    ],
  },
  'visit-prepare': {
    key: 'visit-prepare',
    route: '/chat/visit-prepare',
    title: '准备拜访材料',
    subtitle: '多源输入组合式输出',
    headline: '把主数据、研究、录音和 AI 记忆合成成真正可用的拜访包。',
    description: '页面展示仅主数据、主数据 + 公司分析、主数据 + 录音分析三类数据组合，并固定输出拜访摘要卡、问题清单、风险提示和建议动作。',
    defaultInput: '帮我准备星海精工明天的联合评审拜访材料。',
    prompts: [
      { key: 'v1', label: '仅主数据', description: '快速生成基础拜访提纲。' },
      { key: 'v2', label: '主数据 + 公司分析', description: '补足背景和行业判断。' },
      { key: 'v3', label: '主数据 + 录音分析', description: '补足近期真实交流细节。' },
    ],
    hotTopics: [
      { key: 'vh1', title: '哪些输入会被消费？', description: '主数据、研究快照、录音分析、AI 记忆。' },
      { key: 'vh2', title: '输出为什么固定四块？', description: '方便销售直接拿去用。' },
    ],
    guides: [
      { key: 'vg1', title: '多源输入清晰可见', description: '输入来源明确展示，不做黑盒拼接。' },
      { key: 'vg2', title: '结果直接可执行', description: '摘要、问题、风险、建议动作四块固定结构。' },
    ],
    taskCards: [
      { key: 'vt1', title: '输出结构', status: '4 块', description: '摘要卡、问题清单、风险提示、建议动作。', metric: '统一模板' },
      { key: 'vt2', title: '结果采纳率', status: '78.6%', description: '销售实际采用情况持续上升。', metric: '近 7 日 +6.1%' },
    ],
  },
  tasks: {
    key: 'tasks',
    route: '/chat/tasks',
    title: '我的任务',
    subtitle: '查看任务、资产与写回状态',
    headline: '把聊天里发生的事情变成可追踪的任务和资产。',
    description: '任务中心展示 traceId、taskId、实体锚点、下一步动作和场景状态，并能反查管理员后台。',
    defaultInput: '帮我汇总我今天所有待确认的任务。',
    prompts: [
      { key: 't1', label: '查看待确认写回', description: '聚焦高风险回写与摘要确认。' },
      { key: 't2', label: '查看录音分析进度', description: '按 traceId 追踪状态。' },
      { key: 't3', label: '查看研究快照复用', description: '确认哪些任务可复用已有资产。' },
    ],
    hotTopics: [
      { key: 'th1', title: '任务和会话有什么关系？', description: '会话触发任务，任务沉淀资产。' },
      { key: 'th2', title: '怎么回后台排查？', description: '可直接跳管理员后台看 trace 链路。' },
    ],
    guides: [
      { key: 'tg1', title: '任务可追踪', description: '每个任务都绑定 traceId / taskId。' },
      { key: 'tg2', title: '资产可回看', description: '录音、研究、拜访材料都有资产记录。' },
    ],
    taskCards: [
      { key: 'tt1', title: '任务总数', status: '24 个', description: '当前个人范围内的活动任务。', metric: '3 个高优先级' },
      { key: 'tt2', title: '待确认写回', status: '5 个', description: '金额、阶段、摘要确认为主。', metric: '2 个逾期' },
    ],
  },
};
