import type {
  AgentPlanTemplate,
  AgentPolicy,
  AgentRuntimeTrace,
  AgentToolRow,
  AssetPageConfig,
  AssistantScene,
  AudioImportTask,
  ConversationSession,
  ExternalSkillCatalogItem,
  PageMetric,
  RankingItem,
  RecordPageConfig,
  ResearchSnapshot,
  SceneAssemblyDraft,
  SceneAssemblyKey,
  ScenePlanPlaybook,
  SceneTask,
  SettingPageConfig,
  SystemAlert,
  SystemHealthItem,
  TenantContext,
  TraceLog,
  TrendPoint,
  VisitBrief,
  WritebackPolicy,
} from './types';

const metric = (
  key: string,
  label: string,
  value: string,
  helper: string,
  trend: string,
  status: PageMetric['status'],
): PageMetric => ({
  key,
  label,
  value,
  helper,
  trend,
  status,
});

const timeline = [
  {
    time: '2026-04-23 09:15',
    title: '主数据上下文补齐',
    description: '已自动补齐客户、联系人和商机关联锚点。',
    actor: 'Main Agent',
    status: 'success' as const,
  },
  {
    time: '2026-04-23 09:24',
    title: '生成 TaskPlan',
    description: '根据 IntentFrame、可用工具和治理策略生成可裁剪计划。',
    actor: 'Plan Builder',
    status: 'processing' as const,
  },
  {
    time: '2026-04-23 09:38',
    title: '等待确认或异步回写',
    description: '进入写回确认或资产沉淀阶段，审计链路完整记录。',
    actor: 'Audit Gate',
    status: 'warning' as const,
  },
];

export const tenantContext: TenantContext = {
  eid: 'eid_yzj_cn_hz_001',
  appId: 'app_ai_crm_prod_01',
  tenantName: '云之家华东样板租户',
  suiteName: 'AI销售助手双系统',
  owner: '张晨路',
  region: '华东 2',
  accessStatus: '接入正常',
  orgSyncStatus: '最近一次全量成功',
  lastSyncAt: '2026-04-23 07:40',
  lastHeartbeatAt: '2026-04-23 11:58',
  seatUsage: '128 / 160',
};

export const dashboardMetrics: PageMetric[] = [
  metric('tenant', '租户接入状态', '12 / 12', '已接入租户', '+2 本周', 'healthy'),
  metric('tool', '动态技能就绪率', '96.4%', '对象能力就绪率', '+1.8%', 'healthy'),
  metric('writeback', '主数据写回成功率', '98.2%', '最近 7 日', '+0.6%', 'healthy'),
  metric('audio', '录音导入完成率', '91.3%', '异步链路完成度', '-1.1%', 'attention'),
  metric('research', '研究快照复用率', '63.8%', '用于拜访材料', '+8.5%', 'healthy'),
  metric('security', '跨租户拦截告警', '3', '近 24 小时', '-4', 'attention'),
];

export const dashboardTrendData: TrendPoint[] = [
  { date: '04-17', writebackSuccess: 96.5, audioCompletion: 87.1, researchReuse: 58.2, visitBriefSuccess: 90.2 },
  { date: '04-18', writebackSuccess: 97.0, audioCompletion: 88.9, researchReuse: 59.4, visitBriefSuccess: 91.8 },
  { date: '04-19', writebackSuccess: 97.4, audioCompletion: 90.1, researchReuse: 61.2, visitBriefSuccess: 92.5 },
  { date: '04-20', writebackSuccess: 97.1, audioCompletion: 89.6, researchReuse: 62.8, visitBriefSuccess: 93.1 },
  { date: '04-21', writebackSuccess: 97.8, audioCompletion: 90.8, researchReuse: 63.4, visitBriefSuccess: 93.6 },
  { date: '04-22', writebackSuccess: 98.0, audioCompletion: 91.0, researchReuse: 63.5, visitBriefSuccess: 94.4 },
  { date: '04-23', writebackSuccess: 98.2, audioCompletion: 91.3, researchReuse: 63.8, visitBriefSuccess: 94.8 },
];

export const rankingData: RankingItem[] = [
  { name: '华东制造事业部', value: 94, category: '拜访材料生成成功率' },
  { name: '汽车零部件样板组', value: 91, category: '录音导入完成率' },
  { name: '新能源 KA 组', value: 89, category: '主数据写回成功率' },
  { name: '渠道拓展团队', value: 84, category: '研究快照复用率' },
  { name: '政企业务组', value: 79, category: '技能确认通过率' },
];

export const systemAlerts: SystemAlert[] = [
  {
    id: 'alert-1',
    title: '录音转写回调延迟升高',
    severity: '高',
    description: '华北节点在过去 30 分钟转写回调平均延迟升至 42s，建议检查语音供应商 SLA。',
    owner: '基础平台组',
    updatedAt: '11:46',
  },
  {
    id: 'alert-2',
    title: '跨租户写回拦截命中',
    severity: '中',
    description: '2 条写回请求携带错误 eid，被审计网关成功阻断，需排查调用方缓存。',
    owner: '安全运营组',
    updatedAt: '10:35',
  },
  {
    id: 'alert-3',
    title: '公司研究来源覆盖不足',
    severity: '中',
    description: '部分医药客户研究仅命中 2 个来源，建议调高外部研究兜底阈值。',
    owner: '研究能力组',
    updatedAt: '09:58',
  },
];

export const systemHealth: SystemHealthItem[] = [
  {
    key: 'orchestrator',
    name: '场景编排服务',
    status: 'healthy',
    value: '99.92%',
    target: '99.5%',
    description: '任务编排与重试正常，队列积压低于阈值。',
  },
  {
    key: 'transcript',
    name: '录音转写链路',
    status: 'attention',
    value: '91.3%',
    target: '95%',
    description: '华北节点存在延迟波动，其他区域稳定。',
  },
  {
    key: 'research',
    name: '外部研究服务',
    status: 'healthy',
    value: '6.4 s',
    target: '< 8 s',
    description: '公司分析快照生成时延控制在目标内。',
  },
  {
    key: 'audit',
    name: '确认审计链路',
    status: 'healthy',
    value: '100%',
    target: '100%',
    description: '所有写回均附带 traceId / taskId / eid / appId。',
  },
];

export const recordPages: Record<string, RecordPageConfig> = {
  customers: {
    key: 'customers',
    title: '客户',
    summary: '正式后台列表页，体现影子系统主数据对象与字段元数据，而不是静态写死 schema 的玩具 CRM。',
    searchPlaceholder: '搜索客户名称 / 行业 / 客户编号',
    metrics: [
      metric('count', '对象总量', '1,284', '影子系统客户对象', '+36', 'healthy'),
      metric('sync', '模板同步成功率', '99.1%', '轻云字段元数据同步', '+0.3%', 'healthy'),
      metric('writeback', '确认写回通过率', '94.8%', '最近 7 日客户写回', '+1.5%', 'healthy'),
    ],
    records: [
      {
        id: 'cust-001',
        name: '星海精工股份',
        code: 'CUS-2026-001',
        status: '跟进中',
        owner: '高远',
        industry: '高端装备',
        source: '录音导入',
        updatedAt: '2026-04-23 11:20',
        nextAction: '确认拜访纪要后回写客户标签',
        health: 'healthy',
        tags: ['重点客户', '华东', '录音回写'],
        description: '客户近期关注产线数字化升级，存在多业务线协同机会。',
        related: [
          { label: '最近商机', value: 'AGI 产线升级项目' },
          { label: '客户等级', value: 'A' },
          { label: '最近研究快照', value: '2026-04-22 星海精工研究快照' },
        ],
        timeline,
      },
      {
        id: 'cust-002',
        name: '远澜生物科技',
        code: 'CUS-2026-012',
        status: '待确认',
        owner: '余淼',
        industry: '医药制造',
        source: '公司分析',
        updatedAt: '2026-04-23 10:46',
        nextAction: '补齐采购中心联系人后再触发商机创建',
        health: 'attention',
        tags: ['新客户', '需补齐联系人'],
        description: '研究快照已建立，但联系人与决策链仍不完整。',
        related: [
          { label: '最近任务', value: 'company_research' },
          { label: '联系人数量', value: '2' },
          { label: '待确认字段', value: '采购预算、招标节奏' },
        ],
        timeline,
      },
      {
        id: 'cust-003',
        name: '汇拓能源设备',
        code: 'CUS-2026-018',
        status: '风险关注',
        owner: '宋可欣',
        industry: '新能源装备',
        source: '人工录入',
        updatedAt: '2026-04-22 18:02',
        nextAction: '复核主数据归属，防止跨租户误写',
        health: 'risk',
        tags: ['跨区域', '数据归属待审计'],
        description: '客户曾跨大区流转，主数据归属仍需安全策略确认。',
        related: [
          { label: '审计状态', value: '已拦截 1 次' },
          { label: '负责人', value: '宋可欣' },
          { label: '建议动作', value: '发起管理员复核' },
        ],
        timeline,
      },
    ],
  },
  contacts: {
    key: 'contacts',
    title: '联系人',
    summary: '联系人对象强调角色、影响关系与后续 AI 场景消费，而不是孤立名片列表。',
    searchPlaceholder: '搜索联系人姓名 / 客户 / 角色',
    metrics: [
      metric('count', '对象总量', '3,942', '联系人记录', '+122', 'healthy'),
      metric('relation', '关系边覆盖率', '88.9%', '影响人与决策链', '+4.2%', 'healthy'),
      metric('confirm', '敏感字段确认率', '97.4%', '手机号 / 邮箱确认', '+0.7%', 'healthy'),
    ],
    records: [
      {
        id: 'cont-001',
        name: '杨嘉禾',
        code: 'CON-2026-101',
        status: '已识别决策人',
        owner: '高远',
        phone: '138****2231',
        customerName: '星海精工股份',
        source: '录音导入',
        updatedAt: '2026-04-23 11:12',
        nextAction: '补充其与生产副总的影响关系',
        health: 'healthy',
        tags: ['采购总监', '关键人'],
        description: '在最近录音中确认其参与年度预算拍板。',
        related: [
          { label: '所属客户', value: '星海精工股份' },
          { label: '影响等级', value: 'A' },
          { label: '最近场景', value: '录音导入与拜访分析' },
        ],
        timeline,
      },
      {
        id: 'cont-002',
        name: '何雨潼',
        code: 'CON-2026-122',
        status: '待补齐',
        owner: '余淼',
        phone: '156****9021',
        customerName: '远澜生物科技',
        source: '公司分析',
        updatedAt: '2026-04-23 09:44',
        nextAction: '确认邮箱后触发拜访材料更新',
        health: 'attention',
        tags: ['研究提取', '邮箱缺失'],
        description: '来自公开资料与销售旧记录拼合，仍需人工确认。',
        related: [
          { label: '职位', value: '信息化负责人' },
          { label: '来源', value: '公司分析快照' },
          { label: '确认策略', value: '人工确认' },
        ],
        timeline,
      },
    ],
  },
  opportunities: {
    key: 'opportunities',
    title: '商机',
    summary: '商机页聚焦阶段推进、金额、风险与写回链路，是 AI 场景任务的重要锚点。',
    searchPlaceholder: '搜索商机名称 / 客户 / 阶段',
    metrics: [
      metric('count', '对象总量', '486', '在管商机', '+14', 'healthy'),
      metric('stage', '阶段识别准确率', '92.1%', '由录音与跟进归纳', '+2.1%', 'healthy'),
      metric('risk', '风险商机占比', '13.4%', '需经理复核', '-1.8%', 'attention'),
    ],
    records: [
      {
        id: 'opp-001',
        name: 'AGI 产线升级项目',
        code: 'OPP-2026-009',
        status: '方案评估',
        owner: '高远',
        amount: '¥ 280 万',
        customerName: '星海精工股份',
        source: '录音导入',
        updatedAt: '2026-04-23 11:28',
        nextAction: '生成拜访材料并同步关键风险',
        health: 'healthy',
        tags: ['重点商机', '方案评估'],
        description: '项目已进入联合评估阶段，需准备 ROI 与落地节奏。',
        related: [
          { label: '客户', value: '星海精工股份' },
          { label: '预计关闭', value: '2026-06-30' },
          { label: '最近跟进', value: '2026-04-23 商机跟进记录' },
        ],
        timeline,
      },
      {
        id: 'opp-002',
        name: 'MES 一体化替换',
        code: 'OPP-2026-031',
        status: '待创建',
        owner: '余淼',
        amount: '¥ 90 万',
        customerName: '远澜生物科技',
        source: '公司分析',
        updatedAt: '2026-04-23 10:20',
        nextAction: '客户存在、联系人不足，需先补齐后建商机',
        health: 'attention',
        tags: ['研究导出', '商机待补齐'],
        description: '公司分析识别到项目机会，但主数据上下文尚未闭环。',
        related: [
          { label: '创建条件', value: '需至少 1 个关键联系人' },
          { label: '研究结论', value: '存在预算窗口' },
          { label: '当前状态', value: '草稿' },
        ],
        timeline,
      },
    ],
  },
  followups: {
    key: 'followups',
    title: '商机跟进记录',
    summary: '跟进记录页明确承接录音导入与拜访分析结果，是最关键的 AI 写回结果查看位。',
    searchPlaceholder: '搜索跟进摘要 / 客户 / 商机',
    metrics: [
      metric('count', '对象总量', '2,318', '跟进记录', '+68', 'healthy'),
      metric('audio', '录音入库占比', '54.6%', '来源于录音导入', '+6.3%', 'healthy'),
      metric('confirm', '回写待确认', '37', '高风险写回需确认', '-5', 'attention'),
    ],
    records: [
      {
        id: 'follow-001',
        name: '星海精工 4 月生产数字化拜访',
        code: 'FUP-2026-301',
        status: '已回写',
        owner: '高远',
        customerName: '星海精工股份',
        opportunityName: 'AGI 产线升级项目',
        source: '录音导入',
        updatedAt: '2026-04-23 11:31',
        nextAction: '确认报价材料与内部方案会',
        health: 'healthy',
        tags: ['录音分析', '已回写'],
        description: '已按先补齐上下文、再建跟进记录、最后异步分析的时序完成回写。',
        related: [
          { label: 'traceId', value: 'trace-20260423-001' },
          { label: 'taskId', value: 'task-audio-009' },
          { label: '录音时长', value: '36 分钟' },
        ],
        timeline,
      },
      {
        id: 'follow-002',
        name: '远澜生物调研会记录',
        code: 'FUP-2026-319',
        status: '待确认',
        owner: '余淼',
        customerName: '远澜生物科技',
        opportunityName: 'MES 一体化替换',
        source: '人工补录',
        updatedAt: '2026-04-23 10:48',
        nextAction: '确认商机金额和推进阶段后再回写',
        health: 'attention',
        tags: ['待确认', '金额风险'],
        description: 'AI 已生成摘要和建议动作，但金额字段置信度不足。',
        related: [
          { label: '建议动作', value: '补齐采购节奏' },
          { label: '确认策略', value: '销售经理确认' },
          { label: '风险', value: '金额字段低置信度' },
        ],
        timeline,
      },
    ],
  },
};

export const assetPages: Record<string, AssetPageConfig> = {
  sessions: {
    key: 'sessions',
    title: '会话任务',
    summary: '用于查看用户 AI 端会话、任务推进与实体锚点映射，是管理员观察真实使用链路的核心入口。',
    metrics: [
      metric('session', '活跃会话', '84', '近 24 小时', '+12', 'healthy'),
      metric('task', '任务完成率', '89.6%', 'Agent 计划闭环', '+3.1%', 'healthy'),
      metric('manual', '人工接管', '6.2%', '需要运营协助', '-0.4%', 'attention'),
    ],
    items: [
      {
        id: 'sess-001',
        title: '星海精工 录音导入链路',
        status: '运行中',
        owner: '高远',
        entityAnchor: '客户/星海精工股份',
        summary: '用户从 AI 端发起录音导入，已补齐客户与商机并创建跟进记录。',
        updatedAt: '2026-04-23 11:33',
        score: '92 / 100',
        tags: ['audio-import', 'writeback'],
        timeline,
      },
      {
        id: 'sess-002',
        title: '远澜生物 准备拜访材料',
        status: '待确认',
        owner: '余淼',
        entityAnchor: '客户/远澜生物科技',
        summary: '系统已组合主数据与研究快照，等待销售确认拜访问题清单。',
        updatedAt: '2026-04-23 10:52',
        score: '87 / 100',
        tags: ['visit-prepare', 'research'],
        timeline,
      },
    ],
  },
  'audio-analysis': {
    key: 'audio-analysis',
    title: '录音分析资产',
    summary: '统一查看录音、转写、异步分析、跟进记录回写的全链路资产状态。',
    metrics: [
      metric('asset', '录音资产', '362', '已归档录音', '+28', 'healthy'),
      metric('transcript', '转写成功率', '94.2%', '最近 7 日', '-0.8%', 'attention'),
      metric('latency', '平均完成时长', '12.4 分钟', '从上传到分析完成', '+0.6 分钟', 'attention'),
    ],
    items: [
      {
        id: 'audio-001',
        title: '星海精工 4/23 拜访录音',
        status: '分析完成',
        owner: '高远',
        entityAnchor: '商机/AGI 产线升级项目',
        summary: '已生成跟进摘要、问题清单与风险提示，并绑定至跟进记录。',
        updatedAt: '2026-04-23 11:32',
        score: '36 分钟',
        tags: ['已回写', '会议室录音'],
        timeline,
      },
      {
        id: 'audio-002',
        title: '远澜生物 需求沟通录音',
        status: '等待确认',
        owner: '余淼',
        entityAnchor: '客户/远澜生物科技',
        summary: '客户已匹配成功，但商机金额和阶段仍待确认后回写。',
        updatedAt: '2026-04-23 10:58',
        score: '18 分钟',
        tags: ['金额待确认', '研究补齐'],
        timeline,
      },
    ],
  },
  'research-snapshots': {
    key: 'research-snapshots',
    title: '公司研究快照',
    summary: '研究快照按外部技能资产管理，支持拜访材料、风险分析与任务回看复用。',
    metrics: [
      metric('snapshot', '研究快照', '516', '已沉淀研究资产', '+21', 'healthy'),
      metric('reuse', '复用率', '63.8%', '被下游消费', '+8.5%', 'healthy'),
      metric('freshness', '新鲜度达标', '82.4%', '7 日内更新', '+2.6%', 'healthy'),
    ],
    items: [
      {
        id: 'research-001',
        title: '星海精工 行业与财报快照',
        status: '可复用',
        owner: '研究能力组',
        entityAnchor: '客户/星海精工股份',
        summary: '聚焦产线升级预算、产能扩张计划与竞对动向。',
        updatedAt: '2026-04-22 18:44',
        score: '6 个来源',
        tags: ['财报', '行业资讯'],
        timeline,
      },
      {
        id: 'research-002',
        title: '远澜生物 医药数字化快照',
        status: '待补源',
        owner: '研究能力组',
        entityAnchor: '客户/远澜生物科技',
        summary: '已有招采与行业信息，但缺少近半年舆情和 IT 负责人动态。',
        updatedAt: '2026-04-23 09:16',
        score: '2 个来源',
        tags: ['来源不足', '需扩展'],
        timeline,
      },
    ],
  },
  'visit-briefs': {
    key: 'visit-briefs',
    title: '拜访材料结果',
    summary: '输出拜访摘要卡、问题清单、风险提示与建议动作，服务于销售临门一脚准备。',
    metrics: [
      metric('brief', '拜访材料', '244', '已生成结果', '+19', 'healthy'),
      metric('success', '生成成功率', '94.8%', '最近 7 日', '+2.4%', 'healthy'),
      metric('quality', '人工采纳率', '78.6%', '销售实际采用', '+6.1%', 'healthy'),
    ],
    items: [
      {
        id: 'brief-001',
        title: '星海精工 联合评审拜访包',
        status: '已下发',
        owner: '高远',
        entityAnchor: '客户/星海精工股份',
        summary: '已组合主数据、研究快照、录音分析与 AI 记忆，生成正式拜访提纲。',
        updatedAt: '2026-04-23 11:40',
        score: 'A 级',
        tags: ['主数据+研究+录音'],
        timeline,
      },
      {
        id: 'brief-002',
        title: '远澜生物 初访准备包',
        status: '草稿',
        owner: '余淼',
        entityAnchor: '客户/远澜生物科技',
        summary: '当前仅使用主数据与研究快照，待补齐录音分析后提升完整度。',
        updatedAt: '2026-04-23 10:51',
        score: 'B+',
        tags: ['主数据+研究'],
        timeline,
      },
    ],
  },
};

export const sceneAssemblyDrafts: SceneAssemblyDraft[] = [
  {
    key: 'scene.customer_analysis',
    label: '客户分析',
    category: '分析场景',
    salesStage: '拜访前准备',
    businessGoal: '围绕目标客户汇总客户、联系人、商机和历史跟进，并补充外部公司研究，形成拜访前分析。',
    entityAnchor: '客户',
    summary: '该场景是销售主链路的前置分析节点，强调客户画像、关键关系人、机会盘点和拜访切入点。',
    triggerEntries: [
      '/客户分析 星海精工股份',
      '帮我分析星海精工股份，准备下次拜访',
    ],
    upstreamAssets: ['客户主数据', '联系人记录', '商机记录', '历史跟进记录', '研究快照'],
    outputs: ['客户画像', '关键关系人', '商机盘点', '拜访切入点'],
    orchestrationChain: ['读取客户主数据', '聚合联系人与商机', '补充外部研究', '输出客户分析卡片'],
    recordSkillDependencies: [
      {
        skillName: 'shadow.customer_search',
        objectKey: 'customer',
        operation: 'search',
      },
      {
        skillName: 'shadow.customer_get',
        objectKey: 'customer',
        operation: 'get',
      },
      {
        skillName: 'shadow.contact_search',
        objectKey: 'contact',
        operation: 'search',
      },
      {
        skillName: 'shadow.contact_get',
        objectKey: 'contact',
        operation: 'get',
      },
      {
        skillName: 'shadow.opportunity_search',
        objectKey: 'opportunity',
        operation: 'search',
      },
      {
        skillName: 'shadow.opportunity_get',
        objectKey: 'opportunity',
        operation: 'get',
      },
      {
        skillName: 'shadow.followup_search',
        objectKey: 'followup',
        operation: 'search',
      },
      {
        skillName: 'shadow.followup_get',
        objectKey: 'followup',
        operation: 'get',
      },
    ],
    externalSkillDependencies: [
      {
        skillCode: 'ext.company_research_pm',
        label: '公司研究供给',
      },
    ],
    boundaries: {
      scene: [
        '负责确定客户锚点，并决定需要读取哪些记录系统对象与研究资产。',
        '负责输出客户分析结论，不直接承担主数据维护动作。',
      ],
      shadow: [
        '客户、联系人、商机、跟进记录的结构化读取必须由 shadow.* 技能提供。',
      ],
      external: [
        '外部公司研究仅作为补充背景供给，不直接越权读取或写回 CRM 主数据。',
      ],
      writeback: [
        '该场景默认只消费已确认数据，不直接触发正式写回。',
      ],
    },
  },
  {
    key: 'scene.conversation_understanding',
    label: '拜访会话理解',
    category: '分析场景',
    salesStage: '拜访后第一步',
    businessGoal: '基于拜访录音、纪要和跟进上下文，快速沉淀本次拜访的事实、承诺与风险。',
    entityAnchor: '跟进记录',
    summary: '该场景是拜访后闭环中的首个分析节点，也允许单独通过 slash 或语义直接访问。',
    triggerEntries: [
      '/拜访会话理解 星海精工股份',
      '帮我理解这次星海精工股份的拜访会话',
    ],
    upstreamAssets: ['拜访录音转写', '会话纪要', '跟进记录草稿', '客户与商机上下文'],
    outputs: ['会话摘要', '关键事实', '客户承诺事项', '风险信号'],
    orchestrationChain: ['消费录音转写', '对齐跟进上下文', '抽取事实与承诺', '输出会话理解摘要'],
    recordSkillDependencies: [
      {
        skillName: 'shadow.customer_get',
        objectKey: 'customer',
        operation: 'get',
      },
      {
        skillName: 'shadow.contact_search',
        objectKey: 'contact',
        operation: 'search',
      },
      {
        skillName: 'shadow.opportunity_get',
        objectKey: 'opportunity',
        operation: 'get',
      },
      {
        skillName: 'shadow.followup_get',
        objectKey: 'followup',
        operation: 'get',
      },
    ],
    externalSkillDependencies: [
      {
        skillCode: 'ext.audio_transcribe',
        label: '录音转写',
      },
      {
        skillCode: 'ext.visit_conversation_understanding',
        label: '拜访会话理解供给',
      },
    ],
    boundaries: {
      scene: [
        '负责将录音或纪要转成销售可消费的事实摘要，不直接决定后续写回内容。',
      ],
      shadow: [
        '客户、联系人、商机、跟进记录的上下文读取由 shadow.* 技能负责。',
      ],
      external: [
        '录音转写与语义提炼通过 ext.* 能力供给，不直接变成 CRM 主数据真相。',
      ],
      writeback: [
        '该场景输出为分析资产，写回需要经由后续对象能力确认。',
      ],
    },
  },
  {
    key: 'scene.needs_todo_analysis',
    label: '客户需求工作待办分析',
    category: '分析场景',
    salesStage: '需求澄清',
    businessGoal: '在会话理解基础上识别客户需求、内部待办和下一步责任分工。',
    entityAnchor: '商机 / 跟进记录',
    summary: '该场景强调“客户说了什么、团队接下来做什么”，是从纪要走向执行的中间层。',
    triggerEntries: [
      '/客户需求工作待办分析 星海精工股份',
      '把这次拜访里的需求和待办拆出来',
    ],
    upstreamAssets: ['会话理解结果', '商机阶段', '联系人信息', '历史跟进'],
    outputs: ['需求清单', '客户侧待办', '我方待办', '责任归属建议'],
    orchestrationChain: ['读取会话理解结果', '识别需求与动作', '分配责任归属', '输出待办清单'],
    recordSkillDependencies: [
      {
        skillName: 'shadow.customer_get',
        objectKey: 'customer',
        operation: 'get',
      },
      {
        skillName: 'shadow.contact_search',
        objectKey: 'contact',
        operation: 'search',
      },
      {
        skillName: 'shadow.opportunity_get',
        objectKey: 'opportunity',
        operation: 'get',
      },
      {
        skillName: 'shadow.followup_get',
        objectKey: 'followup',
        operation: 'get',
      },
    ],
    externalSkillDependencies: [
      {
        skillCode: 'ext.customer_needs_todo_analysis',
        label: '客户需求工作待办分析供给',
      },
    ],
    boundaries: {
      scene: [
        '负责把会话信息转成需求与待办视图，不直接修改商机阶段或客户标签。',
      ],
      shadow: [
        '结构化上下文读取仍然由 shadow.* 技能提供。',
      ],
      external: [
        '需求归纳与待办拆解通过 ext.* 能力供给。',
      ],
      writeback: [
        '待办建议默认为分析结果，正式写回需进入确认流程。',
      ],
    },
  },
  {
    key: 'scene.problem_statement',
    label: '问题陈述',
    category: '分析场景',
    salesStage: '方案澄清',
    businessGoal: '将客户需求、约束和风险整理成统一的问题陈述，为方案沟通和内部评审提供口径。',
    entityAnchor: '商机',
    summary: '该场景把散落的需求和背景转成“问题定义”，帮助销售和解决方案团队对齐。',
    triggerEntries: [
      '/问题陈述 星海精工股份',
      '把这次需求整理成问题陈述',
    ],
    upstreamAssets: ['需求待办分析结果', '商机信息', '关键约束与风险'],
    outputs: ['问题背景', '约束条件', '影响范围', '优先级判断'],
    orchestrationChain: ['消费需求待办结果', '整理背景与约束', '输出统一问题陈述'],
    recordSkillDependencies: [
      {
        skillName: 'shadow.customer_get',
        objectKey: 'customer',
        operation: 'get',
      },
      {
        skillName: 'shadow.opportunity_get',
        objectKey: 'opportunity',
        operation: 'get',
      },
      {
        skillName: 'shadow.followup_get',
        objectKey: 'followup',
        operation: 'get',
      },
    ],
    externalSkillDependencies: [
      {
        skillCode: 'ext.problem_statement_pm',
        label: '问题陈述供给',
      },
    ],
    boundaries: {
      scene: [
        '负责形成问题定义，不直接替代客户分析或方案设计。',
      ],
      shadow: [
        '问题陈述所依赖的商机和跟进上下文由 shadow.* 技能读取。',
      ],
      external: [
        '问题框架整理通过 ext.* 能力供给。',
      ],
      writeback: [
        '输出默认沉淀为分析资产，不直接改写正式字段。',
      ],
    },
  },
  {
    key: 'scene.value_positioning',
    label: '客户价值定位',
    category: '分析场景',
    salesStage: '方案澄清',
    businessGoal: '把客户问题、业务目标与金蝶方案价值主张对齐，形成可进入方案推进阶段的价值表达。',
    entityAnchor: '客户 / 商机',
    summary: '该场景仍属于拜访后的分析加工，用来把问题定义进一步收束成价值表达，供后续方案推进场景直接复用。',
    triggerEntries: [
      '/客户价值定位 星海精工股份',
      '帮我形成星海精工股份的价值定位话术',
    ],
    upstreamAssets: ['问题陈述', '客户分析结果', '商机阶段', '历史跟进'],
    outputs: ['客户价值主张', '价值表达口径', '推进话术', '方案推进输入建议'],
    orchestrationChain: ['读取问题陈述', '补充客户背景', '映射价值主张', '输出价值表达与推进输入'],
    recordSkillDependencies: [
      {
        skillName: 'shadow.customer_get',
        objectKey: 'customer',
        operation: 'get',
      },
      {
        skillName: 'shadow.opportunity_get',
        objectKey: 'opportunity',
        operation: 'get',
      },
      {
        skillName: 'shadow.followup_get',
        objectKey: 'followup',
        operation: 'get',
      },
    ],
    externalSkillDependencies: [
      {
        skillCode: 'ext.company_research_pm',
        label: '公司研究供给',
      },
      {
        skillCode: 'ext.customer_value_positioning_pm',
        label: '客户价值定位供给',
      },
    ],
    boundaries: {
      scene: [
        '负责把客户问题翻译成价值表达，为后续方案推进提供统一输入，不直接替代正式报价或方案审批。',
      ],
      shadow: [
        '客户和商机上下文由 shadow.* 技能负责提供。',
      ],
      external: [
        '行业背景与价值表达能力通过 ext.* 引入，用于补强价值论证。',
      ],
      writeback: [
        '价值定位结果默认为辅助销售资产，正式写回仍需单独确认。',
      ],
    },
  },
  {
    key: 'scene.solution_matching',
    label: '方案匹配',
    category: '分析场景',
    salesStage: '方案推进',
    businessGoal: '根据客户诉求和价值定位，在内部方案与案例资产中匹配可推进的候选方案。',
    entityAnchor: '客户 / 商机',
    summary: '该场景承接问题陈述与客户价值定位，负责匹配方案知识和标杆案例，输出销售可继续推进的方案建议。',
    triggerEntries: [
      '/方案匹配 星海精工股份',
      '帮我找和这家客户匹配的方案和案例',
    ],
    upstreamAssets: ['客户价值定位', '问题陈述', '客户诉求摘要', '方案知识库', '标杆案例库'],
    outputs: ['候选方案清单', '匹配案例清单', '方案推进建议'],
    orchestrationChain: ['读取客户诉求与价值定位', '匹配方案知识条目', '筛选相似案例', '生成方案推进建议'],
    recordSkillDependencies: [
      {
        skillName: 'shadow.customer_get',
        objectKey: 'customer',
        operation: 'get',
      },
      {
        skillName: 'shadow.contact_search',
        objectKey: 'contact',
        operation: 'search',
      },
      {
        skillName: 'shadow.opportunity_get',
        objectKey: 'opportunity',
        operation: 'get',
      },
      {
        skillName: 'shadow.followup_get',
        objectKey: 'followup',
        operation: 'get',
      },
    ],
    externalSkillDependencies: [],
    boundaries: {
      scene: [
        '负责把客户诉求翻译成可讨论的候选方案和案例参考，不直接替代正式解决方案设计与审批。',
      ],
      shadow: [
        '客户、联系人、商机和跟进记录上下文仍由 shadow.* 技能读取，场景本身不直接改写正式对象。',
      ],
      external: [
        '公司内部方案知识库和案例库作为供给来源被消费，但在本轮原型中仅做静态表达。',
      ],
      writeback: [
        '输出默认为方案匹配建议，不直接写回报价、项目计划或审批结果。',
      ],
    },
  },
];

const sharedPlanPolicies = [
  {
    confirmation: '写入客户、商机、跟进记录前必须先 preview，再由用户确认。',
    writeback: '分析资产默认不覆盖主数据，正式字段写回仍走 shadow.* 对象能力。',
    pauseResume: '用户可以在任一步暂停，后续从当前 Plan 状态继续。',
    adminBoundary: '管理员维护技能供给、字段权限、确认策略和高风险守卫，不配置固定工作流。',
  },
];

export const scenePlanPlaybooks: Record<SceneAssemblyKey, ScenePlanPlaybook> = {
  'scene.post_visit_loop': {
    sceneKey: 'scene.post_visit_loop',
    planModes: ['最小录入', '先查再建', '完整闭环'],
    stepLibrary: [
      {
        key: 'identify_context',
        label: '识别输入与客户线索',
        description: '读取录音、纪要和当前会话，提取客户名、联系人和拜访意图。',
        requirement: 'required',
        canSkip: false,
        canPause: true,
      },
      {
        key: 'search_customer',
        label: '查询客户',
        description: '通过 shadow.customer_search 查找是否已有客户记录。',
        requirement: 'conditional',
        skillCode: 'shadow.customer_search',
        canSkip: true,
        canPause: true,
      },
      {
        key: 'create_customer',
        label: '创建或补充客户',
        description: '客户不存在或用户只想先录入客户时，生成客户写入预览。',
        requirement: 'conditional',
        skillCode: 'shadow.customer_create',
        canSkip: false,
        canPause: true,
      },
      {
        key: 'resolve_opportunity',
        label: '查询或创建商机',
        description: '按用户目标决定是否复用、选择或新建商机。',
        requirement: 'optional',
        skillCode: 'shadow.opportunity_search',
        canSkip: true,
        canPause: true,
      },
      {
        key: 'create_followup',
        label: '创建跟进记录',
        description: '客户和商机明确后，生成跟进记录写入预览。',
        requirement: 'optional',
        skillCode: 'shadow.followup_create',
        canSkip: true,
        canPause: true,
      },
      {
        key: 'analyze_audio',
        label: '启动录音分析',
        description: '跟进记录创建后再启动转写与会话理解供给。',
        requirement: 'optional',
        skillCode: 'ext.audio_transcribe',
        canSkip: true,
        canPause: true,
      },
      {
        key: 'compose_downstream',
        label: '加入下游分析',
        description: '按需加入需求待办、问题陈述和客户价值定位。',
        requirement: 'optional',
        skillCode: 'ext.customer_needs_todo_analysis',
        canSkip: true,
        canPause: true,
      },
    ],
    variants: [
      {
        key: 'minimal-entry',
        label: '最小录入',
        summary: '只把录音或纪要关联到客户线索，完成客户创建或补充后即可收口。',
        recommendedFor: '用户时间有限，或暂时拿不到商机、联系人和完整拜访信息。',
        steps: ['identify_context', 'create_customer'],
        userDecisions: ['是否跳过客户查询直接创建', '是否把录音仅作为附件留存', '是否稍后继续商机和跟进记录'],
      },
      {
        key: 'search-before-create',
        label: '先查再建',
        summary: '先查客户和商机，命中则复用，未命中再生成创建预览。',
        recommendedFor: '用户不确定系统里是否已有客户，希望避免重复创建。',
        steps: ['identify_context', 'search_customer', 'create_customer', 'resolve_opportunity', 'create_followup'],
        userDecisions: ['客户多候选时选哪一个', '没有商机时是否先建商机', '是否创建跟进记录后暂停'],
      },
      {
        key: 'full-loop',
        label: '完整闭环',
        summary: '从客户和商机锚定一路推进到跟进记录、录音分析和下游销售分析。',
        recommendedFor: '用户希望完整收口一次真实拜访，并让分析资产进入后续复用。',
        steps: ['identify_context', 'search_customer', 'resolve_opportunity', 'create_followup', 'analyze_audio', 'compose_downstream'],
        userDecisions: ['是否补齐联系人', '是否跳过某个分析节点', '是否把分析建议进入写回确认'],
      },
    ],
    policies: sharedPlanPolicies,
    adminControls: ['可用 shadow.* 对象技能', '外部供给 provider', '写入确认策略', '跨租户与权限守卫'],
  },
  'scene.customer_analysis': {
    sceneKey: 'scene.customer_analysis',
    planModes: ['快速客户画像', '拜访前准备'],
    stepLibrary: [
      {
        key: 'resolve_customer',
        label: '确定客户锚点',
        description: '查询并确认客户记录，避免同名客户混用。',
        requirement: 'required',
        skillCode: 'shadow.customer_search',
        canSkip: false,
        canPause: true,
      },
      {
        key: 'collect_crm_context',
        label: '聚合 CRM 上下文',
        description: '读取联系人、商机和历史跟进。',
        requirement: 'conditional',
        skillCode: 'shadow.followup_search',
        canSkip: true,
        canPause: true,
      },
      {
        key: 'add_company_research',
        label: '补充公司研究',
        description: '调用公司研究供给补强公开背景。',
        requirement: 'optional',
        skillCode: 'ext.company_research_pm',
        canSkip: true,
        canPause: true,
      },
    ],
    variants: [
      {
        key: 'quick-profile',
        label: '快速客户画像',
        summary: '只确认客户并输出核心画像，适合临时查看。',
        recommendedFor: '用户只需要快速了解客户是谁。',
        steps: ['resolve_customer'],
        userDecisions: ['是否补充外部研究', '是否继续进入拜访前准备'],
      },
      {
        key: 'visit-prep',
        label: '拜访前准备',
        summary: '聚合 CRM 与公司研究，形成拜访前分析卡片。',
        recommendedFor: '用户准备下一次正式拜访。',
        steps: ['resolve_customer', 'collect_crm_context', 'add_company_research'],
        userDecisions: ['是否聚焦关系人', '是否跳过外部研究', '是否继续生成问题清单'],
      },
    ],
    policies: sharedPlanPolicies,
    adminControls: ['客户查询范围', '研究供给 provider', '来源展示规则', '租户隔离'],
  },
  'scene.conversation_understanding': {
    sceneKey: 'scene.conversation_understanding',
    planModes: ['纪要理解', '录音理解'],
    stepLibrary: [
      {
        key: 'collect_meeting_source',
        label: '收集录音或纪要',
        description: '确认本次会话来源和业务锚点。',
        requirement: 'required',
        canSkip: false,
        canPause: true,
      },
      {
        key: 'read_context',
        label: '读取跟进上下文',
        description: '按需读取客户、商机和跟进记录。',
        requirement: 'conditional',
        skillCode: 'shadow.followup_get',
        canSkip: true,
        canPause: true,
      },
      {
        key: 'understand_conversation',
        label: '生成会话理解',
        description: '输出事实、承诺事项和风险信号。',
        requirement: 'required',
        skillCode: 'ext.visit_conversation_understanding',
        canSkip: false,
        canPause: true,
      },
    ],
    variants: [
      {
        key: 'minutes-only',
        label: '纪要理解',
        summary: '基于用户贴入的纪要快速抽取事实和风险。',
        recommendedFor: '用户没有录音文件，只有文字纪要。',
        steps: ['collect_meeting_source', 'understand_conversation'],
        userDecisions: ['是否补读 CRM 上下文', '是否继续拆需求待办'],
      },
      {
        key: 'audio-with-context',
        label: '录音理解',
        summary: '录音转写后对齐跟进上下文，再生成理解结果。',
        recommendedFor: '用户希望让录音分析资产可复用。',
        steps: ['collect_meeting_source', 'read_context', 'understand_conversation'],
        userDecisions: ['是否等待转写完成', '是否跳过上下文读取'],
      },
    ],
    policies: sharedPlanPolicies,
    adminControls: ['录音供给状态', '跟进记录读取权限', '分析模板版本'],
  },
  'scene.needs_todo_analysis': {
    sceneKey: 'scene.needs_todo_analysis',
    planModes: ['快速待办', '责任拆解'],
    stepLibrary: [
      {
        key: 'load_understanding',
        label: '读取会话理解',
        description: '消费上游会话理解或用户提供的纪要。',
        requirement: 'required',
        canSkip: false,
        canPause: true,
      },
      {
        key: 'split_todos',
        label: '拆分需求和待办',
        description: '生成客户侧待办、我方待办和责任归属建议。',
        requirement: 'required',
        skillCode: 'ext.customer_needs_todo_analysis',
        canSkip: false,
        canPause: true,
      },
    ],
    variants: [
      {
        key: 'quick-todos',
        label: '快速待办',
        summary: '直接基于纪要拆出下一步动作。',
        recommendedFor: '用户要快速整理会后行动项。',
        steps: ['load_understanding', 'split_todos'],
        userDecisions: ['是否指定责任人', '是否进入写回确认'],
      },
      {
        key: 'owner-focused',
        label: '责任拆解',
        summary: '重点识别谁负责、何时完成和阻塞条件。',
        recommendedFor: '用户要推动内部协同。',
        steps: ['load_understanding', 'split_todos'],
        userDecisions: ['是否聚焦我方待办', '是否跳过客户侧待办'],
      },
    ],
    policies: sharedPlanPolicies,
    adminControls: ['待办写回确认', '责任人字段权限', '分析输出模板'],
  },
  'scene.problem_statement': {
    sceneKey: 'scene.problem_statement',
    planModes: ['问题草稿', '评审口径'],
    stepLibrary: [
      {
        key: 'load_problem_inputs',
        label: '读取问题输入',
        description: '消费需求待办、商机和跟进上下文。',
        requirement: 'required',
        skillCode: 'shadow.opportunity_get',
        canSkip: true,
        canPause: true,
      },
      {
        key: 'draft_problem',
        label: '生成问题陈述',
        description: '整理背景、约束、影响范围和优先级。',
        requirement: 'required',
        skillCode: 'ext.problem_statement_pm',
        canSkip: false,
        canPause: true,
      },
    ],
    variants: [
      {
        key: 'draft',
        label: '问题草稿',
        summary: '快速形成可讨论的问题定义。',
        recommendedFor: '用户需要先和团队对齐方向。',
        steps: ['draft_problem'],
        userDecisions: ['是否补读商机上下文', '是否继续价值定位'],
      },
      {
        key: 'review-ready',
        label: '评审口径',
        summary: '补齐上下文后生成可进入内部评审的问题口径。',
        recommendedFor: '用户准备方案会或内部评审。',
        steps: ['load_problem_inputs', 'draft_problem'],
        userDecisions: ['是否强调风险', '是否压缩成一页材料'],
      },
    ],
    policies: sharedPlanPolicies,
    adminControls: ['商机读取权限', '问题陈述模板', '引用来源要求'],
  },
  'scene.value_positioning': {
    sceneKey: 'scene.value_positioning',
    planModes: ['价值话术', '推进输入'],
    stepLibrary: [
      {
        key: 'load_value_inputs',
        label: '读取价值输入',
        description: '读取客户分析、问题陈述和商机上下文。',
        requirement: 'conditional',
        skillCode: 'shadow.customer_get',
        canSkip: true,
        canPause: true,
      },
      {
        key: 'position_value',
        label: '形成价值定位',
        description: '把客户问题映射到金蝶价值主张和推进话术。',
        requirement: 'required',
        skillCode: 'ext.customer_value_positioning_pm',
        canSkip: false,
        canPause: true,
      },
    ],
    variants: [
      {
        key: 'talk-track',
        label: '价值话术',
        summary: '直接生成面向客户沟通的价值表达。',
        recommendedFor: '用户马上要沟通，需要话术。',
        steps: ['position_value'],
        userDecisions: ['是否加入公司研究', '是否继续方案匹配'],
      },
      {
        key: 'enablement-input',
        label: '推进输入',
        summary: '补齐上下文，形成方案推进可复用输入。',
        recommendedFor: '用户准备进入方案匹配阶段。',
        steps: ['load_value_inputs', 'position_value'],
        userDecisions: ['是否强调 ROI', '是否保留风险提示'],
      },
    ],
    policies: sharedPlanPolicies,
    adminControls: ['价值定位模板', '公司研究供给', '方案推进入口'],
  },
  'scene.solution_matching': {
    sceneKey: 'scene.solution_matching',
    planModes: ['方案线索', '案例匹配'],
    stepLibrary: [
      {
        key: 'load_solution_inputs',
        label: '读取方案输入',
        description: '消费问题陈述、价值定位和客户诉求。',
        requirement: 'required',
        skillCode: 'shadow.opportunity_get',
        canSkip: true,
        canPause: true,
      },
      {
        key: 'match_solution_assets',
        label: '匹配方案和案例',
        description: '从内部知识资产中组织候选方案和案例参考。',
        requirement: 'required',
        canSkip: false,
        canPause: true,
      },
    ],
    variants: [
      {
        key: 'solution-leads',
        label: '方案线索',
        summary: '先给销售一个可推进方向和候选案例。',
        recommendedFor: '用户处于早期方案判断。',
        steps: ['match_solution_assets'],
        userDecisions: ['是否只看案例', '是否聚焦交付经验'],
      },
      {
        key: 'case-matching',
        label: '案例匹配',
        summary: '形成候选方案、匹配案例和下一轮推进建议。',
        recommendedFor: '用户准备围绕客户诉求选择可引用方案。',
        steps: ['load_solution_inputs', 'match_solution_assets'],
        userDecisions: ['是否强调 ROI', '是否输出会前材料'],
      },
    ],
    policies: sharedPlanPolicies,
    adminControls: ['内部知识库范围', '案例引用边界', '方案资产版本'],
  },
};

export const externalSkillRows: ExternalSkillCatalogItem[] = [
  {
    id: 'ext-001',
    label: '图片生成',
    skillCode: 'ext.image_generate',
    type: '外部技能',
    trigger: 'Prompt / 品牌海报 / 场景配图',
    dependencies: ['LinkAPI Images API', 'b64_json 预览归一化'],
    status: '运行中',
    implementationType: 'http_request',
    supportsInvoke: true,
    debugMode: 'image_generate',
    debugConfig: {
      artifactKind: 'image',
    },
    provider: 'linkapi_images_provider',
    model: 'gpt-image-2',
    owner: '平台集成组',
    sla: 'P95 < 30 秒',
    summary: '通过 HTTP provider 调用图片生成接口，当前只支持文生图和后台即时预览。',
  },
  {
    id: 'ext-002',
    label: '公司研究供给',
    skillCode: 'ext.company_research_pm',
    type: '外部技能',
    trigger: '客户分析 / 公司研究',
    route: '/chat/customer-analysis',
    dependencies: ['env:DEEPSEEK_API_KEY', 'env:ARK_API_KEY'],
    status: '运行中',
    implementationType: 'skill',
    supportsInvoke: true,
    runtimeSkillName: 'company-research',
    debugMode: 'skill_job',
    debugConfig: {
      defaultModel: 'deepseek-v4-flash',
      supportedModels: ['deepseek-v4-flash', 'deepseek-v4-pro'],
      supportsAttachments: true,
      supportsWorkingDirectory: true,
      requestPlaceholder: '例如：研究绍兴贝斯美化工股份有限公司，输出业务定位、成长驱动、核心风险和来源引用。',
      artifactKind: 'markdown',
    },
    provider: 'skill-runtime',
    model: 'deepseek-v4-flash',
    owner: '研究能力组',
    sla: 'P95 < 10 秒',
    summary: '作为客户分析场景的外部供给能力，补充客户公司的公开背景、风险与机会来源。',
  },
  {
    id: 'ext-003',
    label: '拜访会话理解',
    skillCode: 'ext.visit_conversation_understanding',
    type: '外部技能',
    trigger: '拜访录音 / 会议纪要理解',
    route: '/chat/conversation-understanding',
    dependencies: ['env:DEEPSEEK_API_KEY', '录音转写结果'],
    status: '运行中',
    implementationType: 'skill',
    supportsInvoke: true,
    runtimeSkillName: 'visit-conversation-understanding',
    debugMode: 'skill_job',
    debugConfig: {
      defaultModel: 'deepseek-v4-flash',
      supportedModels: ['deepseek-v4-flash', 'deepseek-v4-pro'],
      supportsAttachments: true,
      supportsWorkingDirectory: true,
      requestPlaceholder: '例如：基于一段客户拜访纪要，输出摘要、关键事实、承诺事项和风险信号。',
      artifactKind: 'markdown',
    },
    provider: 'skill-runtime',
    model: 'deepseek-v4-flash',
    owner: '销售分析能力组',
    sla: 'P95 < 20 秒',
    summary: '负责将拜访录音或纪要整理成可复用的会话理解资产，供后续需求和问题分析复用。',
  },
  {
    id: 'ext-004',
    label: '客户需求工作待办分析',
    skillCode: 'ext.customer_needs_todo_analysis',
    type: '外部技能',
    trigger: '需求澄清 / 待办拆解',
    route: '/chat/needs-todo-analysis',
    dependencies: ['env:DEEPSEEK_API_KEY'],
    status: '运行中',
    implementationType: 'skill',
    supportsInvoke: true,
    runtimeSkillName: 'customer-needs-todo-analysis',
    debugMode: 'skill_job',
    debugConfig: {
      defaultModel: 'deepseek-v4-flash',
      supportedModels: ['deepseek-v4-flash', 'deepseek-v4-pro'],
      supportsAttachments: true,
      supportsWorkingDirectory: true,
      requestPlaceholder: '例如：基于一次客户拜访纪要，拆出客户需求、我方待办和责任归属。',
      artifactKind: 'markdown',
    },
    provider: 'skill-runtime',
    model: 'deepseek-v4-flash',
    owner: '销售分析能力组',
    sla: 'P95 < 20 秒',
    summary: '负责把会话理解结果转成需求清单与执行待办，是拜访后闭环的中间分析节点。',
  },
  {
    id: 'ext-005',
    label: '问题陈述',
    skillCode: 'ext.problem_statement_pm',
    type: '外部技能',
    trigger: '问题定义 / PRD 前置澄清',
    route: '/chat/problem-statement',
    dependencies: ['env:DEEPSEEK_API_KEY'],
    status: '运行中',
    implementationType: 'skill',
    supportsInvoke: true,
    runtimeSkillName: 'problem-statement',
    debugMode: 'skill_job',
    debugConfig: {
      defaultModel: 'deepseek-v4-flash',
      supportedModels: ['deepseek-v4-flash', 'deepseek-v4-pro'],
      supportsAttachments: true,
      supportsWorkingDirectory: true,
      requestPlaceholder: '例如：将“客户资料录入效率低”整理成用户视角的问题陈述和约束背景。',
      artifactKind: 'markdown',
    },
    provider: 'skill-runtime',
    model: 'deepseek-v4-flash',
    owner: '销售分析能力组',
    sla: 'P95 < 20 秒',
    summary: '负责把需求、约束和影响范围整理成统一问题陈述，供方案推进和内部评审使用。',
  },
  {
    id: 'ext-006',
    label: '客户价值定位',
    skillCode: 'ext.customer_value_positioning_pm',
    type: '外部技能',
    trigger: '价值主张梳理 / 方案推进',
    route: '/chat/value-positioning',
    dependencies: ['env:DEEPSEEK_API_KEY'],
    status: '运行中',
    implementationType: 'skill',
    supportsInvoke: true,
    runtimeSkillName: 'customer-value-positioning',
    debugMode: 'skill_job',
    debugConfig: {
      defaultModel: 'deepseek-v4-flash',
      supportedModels: ['deepseek-v4-flash', 'deepseek-v4-pro'],
      supportsAttachments: true,
      supportsWorkingDirectory: true,
      requestPlaceholder: '例如：基于客户问题陈述，输出金蝶可交付的价值主张、推进话术和下一步建议。',
      artifactKind: 'markdown',
    },
    provider: 'skill-runtime',
    model: 'deepseek-v4-flash',
    owner: '销售分析能力组',
    sla: 'P95 < 20 秒',
    summary: '负责把客户问题映射到金蝶价值表达，是从分析结论走向推进话术的外部供给能力。',
  },
  {
    id: 'ext-007',
    label: '录音转写',
    skillCode: 'ext.audio_transcribe',
    type: '外部技能',
    trigger: '音频文件导入',
    route: '/chat',
    dependencies: ['语音服务 Provider', '对象存储'],
    status: '占位中',
    implementationType: 'placeholder',
    supportsInvoke: false,
    debugMode: 'none',
    provider: 'tongyi_agent_provider',
    model: null,
    owner: '语音能力组',
    sla: 'P95 < 5 分钟',
    summary: '作为拜访后闭环的音频入口供给，负责将录音先转成可供后续理解与分析消费的文本资产。',
  },
  {
    id: 'ext-008',
    label: 'super-ppt',
    skillCode: 'ext.super_ppt',
    type: '外部技能',
    trigger: 'Markdown 报告 / 企业研究 PPT 生成',
    route: '/skills/external-skills/super-ppt/editor',
    dependencies: ['env:DOCMEE_API_KEY'],
    status: '运行中',
    implementationType: 'skill',
    supportsInvoke: true,
    runtimeSkillName: 'super-ppt',
    debugMode: 'skill_job',
    debugConfig: {
      defaultModel: null,
      supportedModels: [],
      supportsAttachments: true,
      supportsWorkingDirectory: true,
      requestPlaceholder: '例如：请基于附件生成适合管理层审阅的企业研究汇报 PPT。',
      artifactKind: 'presentation',
    },
    provider: 'docmee-v2',
    model: null,
    owner: '导出能力组',
    sla: 'P95 < 60 秒',
    summary: '通过 Docmee V2 API 将 markdown 企业研究报告生成可继续编辑的 PPT，并支持后台直接进入编辑器。',
  },
];

export const writebackPolicies: WritebackPolicy[] = [
  {
    id: 'policy-001',
    objectKey: 'customer',
    strategy: '关键字段二次确认',
    trigger: '新增客户 / 修改等级 / 修改归属',
    approver: '销售经理',
    auditSampling: '100%',
    rollbackRule: '回滚至最近一次人工确认快照',
    updatedAt: '2026-04-22 15:20',
  },
  {
    id: 'policy-002',
    objectKey: 'followup',
    strategy: '摘要与建议动作确认',
    trigger: '拜访后闭环生成跟进记录',
    approver: '销售本人',
    auditSampling: '30%',
    rollbackRule: '保留 trace 对应草稿版本',
    updatedAt: '2026-04-23 08:46',
  },
];

export const agentToolRows: AgentToolRow[] = [
  {
    id: 'tool-record-customer-search',
    name: '记录对象查询',
    code: 'record.customer.search',
    type: 'record',
    provider: 'lightcloud-shadow',
    status: 'ready',
    riskLevel: 'low',
    confirmationPolicy: 'read_only',
    inputSummary: 'targetType、keyword、filters',
    outputSummary: '候选对象列表、匹配置信度、字段摘要',
    owner: '对象治理组',
    healthNote: '用于 TargetResolution，不直接改写主数据。',
  },
  {
    id: 'tool-record-customer-preview-update',
    name: '记录对象写入预览',
    code: 'record.customer.preview_update',
    type: 'record',
    provider: 'lightcloud-shadow',
    status: 'ready',
    riskLevel: 'high',
    confirmationPolicy: 'required_before_write',
    inputSummary: 'targetRef、fieldPatch、evidenceRefs',
    outputSummary: '写入预览卡、字段差异、确认动作',
    owner: '对象治理组',
    healthNote: '只生成预览，确认后才调用正式写入。',
  },
  {
    id: 'tool-record-followup-preview-create',
    name: '追加记录预览',
    code: 'record.followup.preview_create',
    type: 'record',
    provider: 'lightcloud-shadow',
    status: 'warning',
    riskLevel: 'high',
    confirmationPolicy: 'required_before_write',
    inputSummary: 'targetRefs、content、sourceArtifactRefs',
    outputSummary: '跟进记录草稿、来源证据、确认动作',
    owner: '对象治理组',
    healthNote: 'MVP 可生成草稿，不依赖真实录音转写。',
  },
  {
    id: 'tool-external-company-research',
    name: '公司研究供给',
    code: 'ext.company_research_pm',
    type: 'external',
    provider: 'skill-runtime',
    status: 'ready',
    riskLevel: 'medium',
    confirmationPolicy: 'asset_only',
    inputSummary: 'companyName、researchGoal、industryHint',
    outputSummary: '研究摘要、来源引用、风险与机会',
    owner: '研究能力组',
    healthNote: '作为外部材料供给，不直接成为记录系统主事实。',
  },
  {
    id: 'tool-external-conversation-understanding',
    name: '会话纪要理解',
    code: 'ext.visit_conversation_understanding',
    type: 'external',
    provider: 'skill-runtime',
    status: 'ready',
    riskLevel: 'medium',
    confirmationPolicy: 'asset_only',
    inputSummary: 'meetingNote、contextRefs、artifactRefs',
    outputSummary: '摘要、事实、承诺事项、风险信号',
    owner: '销售分析能力组',
    healthNote: 'MVP 仅消费文字纪要或已有记录，不触发音频转写。',
  },
  {
    id: 'tool-external-audio-transcribe',
    name: '录音转写',
    code: 'ext.audio_transcribe',
    type: 'external',
    provider: 'not_enabled_in_mvp',
    status: 'placeholder',
    riskLevel: 'medium',
    confirmationPolicy: 'disabled_in_mvp',
    inputSummary: 'audioFile',
    outputSummary: 'transcript、speakerSegments、timestamps',
    owner: '语音能力组',
    healthNote: '0.4.5 MVP 明确不接转写，录音只作为附件资产保存。',
  },
  {
    id: 'tool-meta-clarify',
    name: '澄清卡片',
    code: 'meta.clarify_card',
    type: 'meta',
    provider: 'agent-runtime',
    status: 'ready',
    riskLevel: 'low',
    confirmationPolicy: 'user_input_required',
    inputSummary: 'missingSlots、candidateQuestions',
    outputSummary: '用户补充信息、Plan 恢复点',
    owner: 'Agent 平台组',
    healthNote: '用于对象不明确、缺少必要输入或存在高风险歧义。',
  },
  {
    id: 'tool-meta-plan-builder',
    name: '计划生成',
    code: 'meta.plan_builder',
    type: 'meta',
    provider: 'agent-runtime',
    status: 'ready',
    riskLevel: 'low',
    confirmationPolicy: 'editable_by_user',
    inputSummary: 'IntentFrame、availableTools、policyContext',
    outputSummary: 'TaskPlan、步骤依赖、确认点、暂停点',
    owner: 'Agent 平台组',
    healthNote: '根据意图动态生成计划，不命中固定 scene.* 运行时技能。',
  },
  {
    id: 'tool-meta-confirm',
    name: '确认写回',
    code: 'meta.confirm_writeback',
    type: 'meta',
    provider: 'agent-runtime',
    status: 'ready',
    riskLevel: 'high',
    confirmationPolicy: 'required_before_write',
    inputSummary: 'previewId、userDecision、auditContext',
    outputSummary: '确认结果、审计事件、执行状态',
    owner: 'Agent 平台组',
    healthNote: '所有写主数据动作都必须经过该确认守卫。',
  },
];

export const agentPlanTemplates: AgentPlanTemplate[] = [
  {
    id: 'tpl-pre-visit-research',
    name: '拜访前准备',
    intentPattern: '分析目标对象并生成会前材料',
    summary: '面向“明天拜访某公司 / 帮我看下这个客户”这类请求，推荐先查记录对象，再补充外部研究和问题清单。',
    sampleUtterances: ['明天拜访华东医药，帮我准备下', '帮我看下这个客户，别重复问历史问题'],
    status: 'enabled',
    steps: [
      {
        key: 'resolve-target',
        title: '识别并确认目标对象',
        actionType: 'meta',
        toolRefs: ['meta.clarify_card', 'record.customer.search'],
        required: true,
        skippable: false,
        confirmationRequired: false,
      },
      {
        key: 'collect-context',
        title: '读取内部上下文',
        actionType: 'query',
        toolRefs: ['record.customer.search'],
        required: true,
        skippable: false,
        confirmationRequired: false,
      },
      {
        key: 'add-research',
        title: '补充外部研究',
        actionType: 'external',
        toolRefs: ['ext.company_research_pm'],
        required: false,
        skippable: true,
        confirmationRequired: false,
      },
    ],
    outputs: ['拜访摘要', '关键关系与历史接触', '建议提问', '证据引用'],
    governanceNotes: ['结论必须带来源；未找到对象时允许生成临时研究材料。'],
  },
  {
    id: 'tpl-post-visit-light',
    name: '拜访后轻量整理',
    intentPattern: '整理已有文字材料，并在可信时补充记录对象',
    summary: '面向“这段录音先帮我整理下，客户信息能补就补”。MVP 不做转写，只消费文字纪要或已有记录。',
    sampleUtterances: ['这段录音先帮我整理下，客户信息能补就补', '先保存纪要，客户信息晚点确认'],
    status: 'enabled',
    steps: [
      {
        key: 'save-artifact',
        title: '保存附件或文字材料',
        actionType: 'meta',
        toolRefs: ['meta.plan_builder'],
        required: true,
        skippable: false,
        confirmationRequired: false,
      },
      {
        key: 'understand-note',
        title: '理解文字纪要',
        actionType: 'analyze',
        toolRefs: ['ext.visit_conversation_understanding'],
        required: false,
        skippable: true,
        confirmationRequired: false,
      },
      {
        key: 'preview-writeback',
        title: '生成补录预览',
        actionType: 'write_preview',
        toolRefs: ['record.customer.preview_update'],
        required: false,
        skippable: true,
        confirmationRequired: true,
      },
    ],
    outputs: ['整理摘要', '对象候选', '补录预览', '挂起状态'],
    governanceNotes: ['只有录音无文字时不触发分析；写入前必须 preview + confirm。'],
  },
  {
    id: 'tpl-customer-blocker',
    name: '对象阶段与卡点分析',
    intentPattern: '查询目标对象当前阶段、卡点和下一步',
    summary: '面向“这个客户现在卡在哪里 / 下一步怎么办”这类请求，动态组合查询、分析和证据输出。',
    sampleUtterances: ['这个客户现在卡在哪里', '帮我列一下这个客户接下来怎么推'],
    status: 'enabled',
    steps: [
      {
        key: 'resolve-target',
        title: '确认目标对象',
        actionType: 'meta',
        toolRefs: ['meta.clarify_card', 'record.customer.search'],
        required: true,
        skippable: false,
        confirmationRequired: false,
      },
      {
        key: 'analyze-evidence',
        title: '基于证据分析卡点',
        actionType: 'analyze',
        toolRefs: ['ext.problem_statement_pm'],
        required: true,
        skippable: false,
        confirmationRequired: false,
      },
    ],
    outputs: ['阶段判断', '主要卡点', '证据引用', '下一步建议'],
    governanceNotes: ['没有证据时必须降级为“不足以判断”，不得编造确定结论。'],
  },
];

export const agentPolicies: AgentPolicy[] = [
  {
    id: 'policy-agent-write-confirm',
    name: '写主数据必须确认',
    target: 'record.*.create / record.*.update / record.*.append',
    trigger: '任何写入正式记录系统的动作',
    action: 'require_confirmation',
    severity: 'high',
    owner: 'Agent 平台组',
    lastTriggered: '2026-04-27 15:32',
  },
  {
    id: 'policy-agent-no-audio-transcribe-mvp',
    name: 'MVP 禁用录音转写',
    target: 'ext.audio_transcribe',
    trigger: '用户仅上传录音且未提供文字纪要',
    action: 'downgrade_to_draft',
    severity: 'medium',
    owner: '语音能力组',
    lastTriggered: '2026-04-27 14:08',
  },
  {
    id: 'policy-agent-evidence-required',
    name: '分析结论必须带证据',
    target: 'analyze / recommendation',
    trigger: '输出阶段判断、关注点、卡点、风险等结论',
    action: 'audit',
    severity: 'medium',
    owner: 'Agent 平台组',
    lastTriggered: '2026-04-27 16:20',
  },
  {
    id: 'policy-agent-cross-tenant',
    name: '跨租户引用拦截',
    target: 'all tools',
    trigger: '工具输入或证据引用的 eid/appId 与当前上下文不一致',
    action: 'block',
    severity: 'high',
    owner: '安全运营组',
    lastTriggered: '2026-04-26 18:11',
  },
];

export const agentRuntimeTraces: AgentRuntimeTrace[] = [
  {
    id: 'runtime-001',
    userInput: '这段录音先帮我整理下，客户信息能补就补',
    intentFrame: {
      actionType: 'plan',
      goal: '整理已有材料，并在可信时补充记录对象信息',
      targets: ['customer: 星海精工股份'],
      missingSlots: ['文字纪要或可消费的会话材料'],
    },
    taskPlan: {
      planId: 'plan-20260427-001',
      status: 'waiting_input',
      steps: ['保存附件', '等待文字材料', '查询对象候选', '生成补录预览'],
    },
    executionState: 'paused_waiting_note',
    toolChain: ['meta.plan_builder', 'record.customer.search'],
    evidenceRefs: ['message:当前用户输入', 'artifact:audio-placeholder'],
    result: 'MVP 未触发转写，已保存附件并等待用户补充文字纪要。',
    timestamp: '2026-04-27 16:42:11',
  },
  {
    id: 'runtime-002',
    userInput: '先查一下有没有这个客户，没有再建',
    intentFrame: {
      actionType: 'plan',
      goal: '先查询目标对象，未命中时生成创建预览',
      targets: ['customer: 苏州星河智能'],
      missingSlots: [],
    },
    taskPlan: {
      planId: 'plan-20260427-002',
      status: 'waiting_confirmation',
      steps: ['查询对象', '展示候选', '创建预览', '等待确认'],
    },
    executionState: 'waiting_confirmation',
    toolChain: ['record.customer.search', 'record.customer.preview_update', 'meta.confirm_writeback'],
    evidenceRefs: ['record-search:candidate-list', 'message:user-confirmation-pending'],
    result: '未找到高置信候选，已生成创建预览等待用户确认。',
    timestamp: '2026-04-27 16:48:37',
  },
  {
    id: 'runtime-003',
    userInput: '这个客户现在卡在哪里',
    intentFrame: {
      actionType: 'analyze',
      goal: '基于已有记录和证据分析目标对象卡点',
      targets: ['customer: 远澜生物'],
      missingSlots: [],
    },
    taskPlan: {
      planId: 'plan-20260427-003',
      status: 'completed',
      steps: ['确认目标对象', '读取上下文', '分析证据', '输出卡点'],
    },
    executionState: 'completed',
    toolChain: ['record.customer.search', 'ext.problem_statement_pm'],
    evidenceRefs: ['followup:2026-04-18', 'research:snapshot-0420'],
    result: '输出阶段判断、卡点和下一步建议，并标注依据来源。',
    timestamp: '2026-04-27 17:01:05',
  },
];

export const traceLogs: TraceLog[] = [
  {
    traceId: 'trace-20260423-001',
    taskId: 'task-loop-009',
    eid: tenantContext.eid,
    appId: tenantContext.appId,
    scene: 'scene.post_visit_loop',
    status: '成功',
    toolChain: [
      'shadow.customer.search',
      'shadow.opportunity.search',
      'shadow.followup.create',
      'ext.audio_transcribe',
      'scene.conversation_understanding',
      'scene.needs_todo_analysis',
    ],
    writebackResult: '客户、商机与跟进记录已锚定，会话理解与待办分析资产已沉淀',
    timestamp: '2026-04-23 11:32:14',
  },
  {
    traceId: 'trace-20260423-017',
    taskId: 'task-analysis-013',
    eid: tenantContext.eid,
    appId: tenantContext.appId,
    scene: 'scene.customer_analysis',
    status: '成功',
    toolChain: [
      'shadow.customer.get',
      'shadow.contact.search',
      'shadow.opportunity.search',
      'ext.company_research_pm',
    ],
    writebackResult: '客户分析卡片已生成，研究快照作为外部供给被复用',
    timestamp: '2026-04-23 09:18:22',
  },
  {
    traceId: 'trace-20260423-021',
    taskId: 'task-problem-004',
    eid: tenantContext.eid,
    appId: tenantContext.appId,
    scene: 'scene.problem_statement',
    status: '成功',
    toolChain: [
      'scene.needs_todo_analysis',
      'shadow.opportunity.get',
      'shadow.followup.get',
      'ext.problem_statement_pm',
    ],
    writebackResult: '问题陈述结果已落盘，并可供客户价值定位继续消费',
    timestamp: '2026-04-23 10:51:03',
  },
];

export const settingPages: Record<string, SettingPageConfig> = {
  'tenant-app': {
    key: 'tenant-app',
    title: '租户 / 应用识别',
    summary: '维护租户、应用实例、访问域和环境隔离，是双系统共享上下文的起点。',
    metrics: [
      metric('eid', '租户识别', tenantContext.eid, '当前活动租户', '稳定', 'healthy'),
      metric('app', '应用实例', tenantContext.appId, '当前活动应用', '稳定', 'healthy'),
    ],
    groups: [
      {
        key: 'tenant',
        title: '基础识别',
        summary: '定义管理员后台和用户 AI 端共享的租户上下文。',
        tags: ['eid', 'appId', 'environment'],
        healthNote: '当前双系统均已绑定同一业务域上下文。',
        fields: [
          { name: 'tenantName', label: '租户名称', value: tenantContext.tenantName, kind: 'text' },
          { name: 'suiteName', label: '套件名称', value: tenantContext.suiteName, kind: 'text' },
          { name: 'eid', label: 'eid', value: tenantContext.eid, kind: 'text' },
          { name: 'appId', label: 'appId', value: tenantContext.appId, kind: 'text' },
          { name: 'region', label: '部署区域', value: tenantContext.region, kind: 'select', options: ['华东 2', '华南 1', '华北 1'] },
        ],
      },
      {
        key: 'access',
        title: '访问约束',
        summary: '控制回调域、单点入口和租户隔离策略。',
        tags: ['domain', 'callback', 'isolation'],
        healthNote: '跨租户拦截已启用，审计链路完整。',
        fields: [
          { name: 'adminDomain', label: '后台域名', value: 'https://admin.ai-crm.yzj.mock', kind: 'text' },
          { name: 'assistantDomain', label: 'AI 端域名', value: 'https://assistant.ai-crm.yzj.mock', kind: 'text' },
          { name: 'enforceIsolation', label: '强制租户隔离', value: true, kind: 'switch' },
        ],
      },
    ],
  },
  'yzj-auth': {
    key: 'yzj-auth',
    title: '云之家接入',
    summary: '配置 OAuth、服务端签名与轻云权限，是系统接入的基础能力。',
    metrics: [
      metric('oauth', 'OAuth 状态', '已连接', '最近心跳正常', '稳定', 'healthy'),
      metric('sign', '签名校验', '100%', '最近 24 小时', '稳定', 'healthy'),
    ],
    groups: [
      {
        key: 'oauth',
        title: 'OAuth 与应用凭证',
        summary: '维护回调地址、客户端凭证与票据刷新策略。',
        tags: ['oauth', 'token'],
        healthNote: '票据刷新成功率 100%。',
        fields: [
          { name: 'clientId', label: 'Client ID', value: 'yzj-demo-client-id', kind: 'text' },
          { name: 'redirect', label: '回调地址', value: 'https://admin.ai-crm.yzj.mock/oauth/callback', kind: 'text' },
          { name: 'tokenRefresh', label: '自动刷新 Token', value: true, kind: 'switch' },
        ],
      },
      {
        key: 'lightcloud',
        title: '轻云权限范围',
        summary: '控制记录系统对象的读写权限。',
        tags: ['lightcloud', 'permission'],
        healthNote: '客户、联系人、商机、跟进记录权限均已授予。',
        fields: [
          { name: 'scopes', label: '授权范围', value: 'customer, contact, opportunity, followup', kind: 'textarea' },
          { name: 'signatureMode', label: '签名模式', value: 'HMAC-SHA256', kind: 'select', options: ['HMAC-SHA256', 'RSA'] },
        ],
      },
    ],
  },
  'org-sync': {
    key: 'org-sync',
    title: '组织同步',
    summary: '同步部门、成员、岗位与汇报关系，为联系人归属和权限判断提供基础。',
    metrics: [
      metric('full', '全量同步', '每日 01:00', '最近一次成功', '稳定', 'healthy'),
      metric('delta', '增量延迟', '4 分钟', '最近 24 小时', '+1 分钟', 'healthy'),
    ],
    groups: [
      {
        key: 'sync',
        title: '同步调度',
        summary: '全量 + 增量双模式运行。',
        tags: ['full', 'delta'],
        healthNote: '组织树未发现断链。',
        fields: [
          { name: 'fullSync', label: '全量同步 Cron', value: '每日 01:00', kind: 'text' },
          { name: 'deltaSync', label: '增量同步间隔', value: '5 分钟', kind: 'select', options: ['5 分钟', '10 分钟', '15 分钟'] },
          { name: 'syncManager', label: '同步负责人', value: '基础平台组', kind: 'text' },
        ],
      },
    ],
  },
  models: {
    key: 'models',
    title: '模型 / 转写 / 研究 / 存储',
    summary: '统一管理主模型、转写、研究 Provider 与资产存储策略。',
    metrics: [
      metric('model', '主模型可用性', '99.5%', '最近 7 日', '+0.2%', 'healthy'),
      metric('storage', '对象存储可用性', '99.99%', '最近 30 日', '稳定', 'healthy'),
    ],
    groups: [
      {
        key: 'model',
        title: '主模型',
        summary: '负责 AI 对话、任务编排与拜访材料生成。',
        tags: ['llm', 'reasoning'],
        healthNote: '主模型和回退模型均可用。',
        fields: [
          { name: 'primaryModel', label: '主模型', value: 'glm-4.5-flash / mock', kind: 'text' },
          { name: 'fallbackModel', label: '回退模型', value: 'qwen-plus / mock', kind: 'text' },
          { name: 'enableThought', label: '启用思考输出', value: true, kind: 'switch' },
        ],
      },
      {
        key: 'audio',
        title: '录音转写',
        summary: '负责音频识别与段落切分。',
        tags: ['audio', 'transcript'],
        healthNote: '华北节点延迟偏高，其他节点正常。',
        fields: [
          { name: 'transcriptProvider', label: '转写 Provider', value: 'tongyi-agent / mock', kind: 'text' },
          { name: 'maxDuration', label: '单文件时长上限', value: '90 分钟', kind: 'select', options: ['60 分钟', '90 分钟', '120 分钟'] },
        ],
      },
      {
        key: 'research',
        title: '公司研究',
        summary: '负责外部检索与研究快照沉淀。',
        tags: ['research', 'snapshot'],
        healthNote: '医药行业来源覆盖需增强。',
        fields: [
          { name: 'searchDepth', label: '默认检索深度', value: '标准', kind: 'select', options: ['标准', '增强'] },
          { name: 'snapshotTtl', label: '快照有效期', value: '7 天', kind: 'select', options: ['3 天', '7 天', '14 天'] },
        ],
      },
    ],
  },
  observability: {
    key: 'observability',
    title: '可观测性',
    summary: '聚焦 traceId / taskId / eid / appId、tool 调用链与写回结果，支持管理员定位场景问题。',
    metrics: [
      metric('trace', 'Trace 完整率', '100%', '所有任务均带上下文', '稳定', 'healthy'),
      metric('audit', '写回审计覆盖率', '100%', '高风险操作全量记录', '稳定', 'healthy'),
    ],
    groups: [
      {
        key: 'trace',
        title: '追踪上下文',
        summary: '统一记录 traceId / taskId / eid / appId。',
        tags: ['traceId', 'taskId', 'eid', 'appId'],
        healthNote: '当前所有链路均可追踪到上下文。',
        fields: [
          { name: 'traceExport', label: 'Trace 导出', value: 'OpenTelemetry / mock', kind: 'text' },
          { name: 'traceRetention', label: '保留周期', value: '90 天', kind: 'select', options: ['30 天', '90 天', '180 天'] },
          { name: 'enableAudit', label: '启用写回审计', value: true, kind: 'switch' },
        ],
      },
    ],
  },
  security: {
    key: 'security',
    title: '安全与运营',
    summary: '覆盖跨租户拦截、字段脱敏、人工接管和异常处理策略。',
    metrics: [
      metric('block', '跨租户拦截', '100%', '应拦截请求全部阻断', '稳定', 'healthy'),
      metric('mask', '敏感字段脱敏', '100%', '手机号 / 邮箱等', '稳定', 'healthy'),
    ],
    groups: [
      {
        key: 'security',
        title: '风险控制',
        summary: '保障正式后台和 AI 端的共享数据安全。',
        tags: ['masking', 'handoff', 'audit'],
        healthNote: '未发生高危越权事件。',
        fields: [
          { name: 'crossTenantBlock', label: '跨租户写回拦截', value: true, kind: 'switch' },
          { name: 'manualHandoff', label: '人工接管开关', value: true, kind: 'switch' },
          { name: 'piiMasking', label: 'PII 脱敏规则', value: '手机号 / 邮箱 / 身份标识', kind: 'textarea' },
        ],
      },
    ],
  },
};

export const conversationSessions: ConversationSession[] = [
  {
    key: 'conv-customer-analysis',
    label: '客户分析',
    route: '/chat/customer-analysis',
    group: '固定会话',
    lastMessage: '拜访前先看客户画像、关系人、商机盘点和切入点。',
    updatedAt: '10:52',
    scene: 'customer-analysis',
  },
  {
    key: 'conv-conversation-understanding',
    label: '拜访会话理解',
    route: '/chat/conversation-understanding',
    group: '固定会话',
    lastMessage: '沉淀本次拜访的事实、承诺事项和风险信号。',
    updatedAt: '10:26',
    scene: 'conversation-understanding',
  },
  {
    key: 'conv-needs-todo',
    label: '客户需求工作待办分析',
    route: '/chat/needs-todo-analysis',
    group: '固定会话',
    lastMessage: '把客户需求、我方待办和责任分工拆清楚。',
    updatedAt: '09:58',
    scene: 'needs-todo-analysis',
  },
  {
    key: 'conv-problem-statement',
    label: '问题陈述',
    route: '/chat/problem-statement',
    group: '固定会话',
    lastMessage: '把需求和约束整理成统一的问题定义。',
    updatedAt: '09:22',
    scene: 'problem-statement',
  },
  {
    key: 'conv-value-positioning',
    label: '客户价值定位',
    route: '/chat/value-positioning',
    group: '固定会话',
    lastMessage: '把客户问题映射成金蝶价值主张，作为方案推进输入。',
    updatedAt: '昨天',
    scene: 'value-positioning',
  },
  {
    key: 'conv-solution-matching',
    label: '方案匹配',
    route: '/chat/solution-matching',
    group: '固定会话',
    lastMessage: '围绕客户诉求匹配内部方案和案例。',
    updatedAt: '昨天',
    scene: 'solution-matching',
  },
  {
    key: 'conv-tasks',
    label: '我的任务',
    route: '/chat/tasks',
    group: '固定会话',
    lastMessage: '查看 trace、任务状态和待确认写回。',
    updatedAt: '昨天',
    scene: 'tasks',
  },
];

export const sceneTasks: SceneTask[] = [
  {
    id: 'task-loop-009',
    title: '星海精工录音处理 Plan',
    scene: '复合 Plan',
    route: '/chat/tasks',
    status: '运行中',
    progress: 82,
    owner: '高远',
    entityAnchor: '商机/AGI 产线升级项目',
    nextAction: '确认跟进记录草稿并查看问题陈述草案',
    traceId: 'trace-20260423-001',
    taskId: 'task-loop-009',
    eid: tenantContext.eid,
    appId: tenantContext.appId,
    updatedAt: '11:32',
  },
  {
    id: 'task-analysis-013',
    title: '星海精工客户分析',
    scene: '客户分析',
    route: '/chat/customer-analysis',
    status: '已完成',
    progress: 100,
    owner: '余淼',
    entityAnchor: '客户/星海精工股份',
    nextAction: '复用客户分析结果进入客户价值定位',
    traceId: 'trace-20260423-017',
    taskId: 'task-analysis-013',
    eid: tenantContext.eid,
    appId: tenantContext.appId,
    updatedAt: '09:18',
  },
  {
    id: 'task-problem-004',
    title: '远澜生物问题陈述',
    scene: '问题陈述',
    route: '/chat/problem-statement',
    status: '已完成',
    progress: 100,
    owner: '高远',
    entityAnchor: '客户/远澜生物科技',
    nextAction: '进入客户价值定位，形成推进话术',
    traceId: 'trace-20260423-021',
    taskId: 'task-problem-004',
    eid: tenantContext.eid,
    appId: tenantContext.appId,
    updatedAt: '10:51',
  },
];

export const researchSnapshots: ResearchSnapshot[] = [
  {
    id: 'snap-001',
    companyName: '星海精工股份',
    intent: '客户分析 / 联合评审拜访',
    sourceCount: 6,
    freshness: '1 天内',
    owner: '研究能力组',
    updatedAt: '2026-04-22 18:44',
    summary: '公司正推进产线升级和海外交付体系重构，预算窗口明确，重点关注 ROI 和交付周期。',
    citations: [
      { title: '2025 年年报摘要', source: '企业公开披露' },
      { title: '行业协会产线升级观察', source: '行业报告' },
      { title: '最近 30 天新闻提及', source: '媒体聚合' },
    ],
    risks: ['采购流程跨部门审批较长', '竞争对手已提前进场'],
    opportunities: ['预算已列入 CAPEX', '工厂数字化 KPI 明确'],
  },
  {
    id: 'snap-002',
    companyName: '远澜生物科技',
    intent: '客户分析 / 初访准备',
    sourceCount: 2,
    freshness: '4 小时内',
    owner: '研究能力组',
    updatedAt: '2026-04-23 09:16',
    summary: '公司具备数字化改造意愿，但采购链与 IT 负责人公开信息有限。',
    citations: [
      { title: '行业资讯摘录', source: '公开资讯' },
      { title: '企业官网公告', source: '企业官网' },
    ],
    risks: ['来源数量不足', '关键信息需人工核实'],
    opportunities: ['信息化改造正在预算讨论期'],
  },
];

export const audioImportTasks: AudioImportTask[] = [
  {
    id: 'audio-task-001',
    title: '星海精工 4/23 拜访录音',
    branch: '有客户有商机',
    customerName: '星海精工股份',
    opportunityName: 'AGI 产线升级项目',
    duration: '36 分钟',
    transcriptStatus: '已转写',
    analysisStatus: '已分析',
    writebackStatus: '已回写',
    progress: 100,
    owner: '高远',
    updatedAt: '11:32',
    steps: [
      { title: '校验客户上下文', status: 'completed', description: '命中客户与关键联系人。' },
      { title: '校验商机上下文', status: 'completed', description: '命中商机并识别当前阶段。' },
      { title: '创建跟进记录草稿', status: 'completed', description: '先建记录，再进入异步分析。' },
      { title: '异步分析录音', status: 'completed', description: '生成摘要、风险与建议动作。' },
    ],
  },
  {
    id: 'audio-task-002',
    title: '远澜生物 需求沟通录音',
    branch: '有客户无商机',
    customerName: '远澜生物科技',
    duration: '18 分钟',
    transcriptStatus: '已转写',
    analysisStatus: '分析中',
    writebackStatus: '待确认',
    progress: 72,
    owner: '余淼',
    updatedAt: '10:58',
    steps: [
      { title: '校验客户上下文', status: 'completed', description: '客户已存在。' },
      { title: '校验商机上下文', status: 'warning', description: '未命中商机，需先补齐。' },
      { title: '创建跟进记录草稿', status: 'completed', description: '已先建跟进记录草稿。' },
      { title: '异步分析录音', status: 'running', description: '等待金额与阶段确认。' },
    ],
  },
  {
    id: 'audio-task-003',
    title: '渠道拓展陌生拜访录音',
    branch: '无客户无商机',
    duration: '12 分钟',
    transcriptStatus: '已转写',
    analysisStatus: '待补齐上下文',
    writebackStatus: '未开始',
    progress: 34,
    owner: '赵天一',
    updatedAt: '09:42',
    steps: [
      { title: '校验客户上下文', status: 'warning', description: '客户不存在，需先创建。' },
      { title: '校验商机上下文', status: 'draft', description: '需客户存在后才能建商机。' },
      { title: '创建跟进记录草稿', status: 'draft', description: '等待上下文补齐。' },
      { title: '异步分析录音', status: 'draft', description: '未进入分析阶段。' },
    ],
  },
];

export const visitBriefs: VisitBrief[] = [
  {
    id: 'brief-view-001',
    customerName: '星海精工股份',
    theme: '联合评审会前准备',
    owner: '高远',
    updatedAt: '2026-04-23 11:40',
    sourceMix: ['主数据', '公司研究快照', '录音分析', 'AI 记忆'],
    summary: [
      '客户预算已在本季度 CAPEX 中明确，决策链以采购总监和生产副总为核心。',
      '最近录音确认客户关心交付周期、ROI 和对现有 MES 的迁移风险。',
    ],
    questions: [
      '客户最担心的停产窗口具体是几天？',
      '采购部与生产部谁拥有最终项目拍板权？',
      '是否需要提供分阶段上线方案与回滚计划？',
    ],
    risks: [
      '竞争对手已先行提供初步报价。',
      'IT 与生产部门目标不完全一致。',
    ],
    actions: ['准备 ROI 对比表', '准备分阶段上线计划', '会后 24 小时内形成确认纪要'],
  },
  {
    id: 'brief-view-002',
    customerName: '远澜生物科技',
    theme: '初访准备',
    owner: '余淼',
    updatedAt: '2026-04-23 10:51',
    sourceMix: ['主数据', '公司研究快照'],
    summary: ['已知客户对数字化改造有兴趣，但关键联系人和预算信息仍不足。'],
    questions: ['此次拜访是否以信息化调研为主，还是已有明确项目？', '预算讨论周期是否在本季度？'],
    risks: ['公开来源不足，需注意信息过度推断。'],
    actions: ['优先确认联系人地图', '获取项目背景材料'],
  },
];

export const assistantScenes: Record<string, AssistantScene> = {
  chat: {
    key: 'chat',
    route: '/chat',
    title: 'AI 销售工作台',
    subtitle: 'Plan 驱动工作台',
    headline: '先理解目标并生成建议 Plan，再由用户裁剪、确认和逐步推进。',
    description: '首页支持直接表达业务目标。你可以只说“这段录音先帮我录入客户就行”，也可以要求“先查一下有没有这个客户，没有再建”，或让系统生成完整录音处理 Plan。',
    defaultInput: '这段录音先帮我录入客户就行',
    prompts: [
      { key: 'p1', label: '这段录音先帮我录入客户就行', description: '生成最小录入 Plan，只完成客户创建或补充。' },
      { key: 'p2', label: '先查一下有没有这个客户，没有再建', description: '生成先查再建 Plan，避免重复创建客户。' },
      { key: 'p3', label: '这段拜访录音帮我完整处理', description: '生成完整录音处理 Plan，再逐步确认执行。' },
      { key: 'p4', label: '/客户分析 星海精工股份', description: '生成客户分析 Plan，先看客户画像和商机盘点。' },
      { key: 'p5', label: '/客户价值定位 星海精工股份', description: '形成金蝶价值主张和推进话术。' },
      { key: 'p6', label: '/方案匹配 星海精工股份', description: '匹配内部方案和可引用案例。' },
    ],
    hotTopics: [
      { key: 'h1', title: '这段录音先帮我录入客户就行', description: '最小录入：先把客户信息沉淀下来，其他步骤可跳过。' },
      { key: 'h2', title: '先查一下有没有这个客户，没有再建', description: '先查再建：减少重复记录，必要时再生成写入预览。' },
      { key: 'h3', title: '这段拜访录音帮我完整处理', description: '完整处理：客户、商机、跟进、录音分析和下游分析逐步确认。' },
      { key: 'h4', title: '/方案匹配 星海精工股份', description: '分步入口：围绕客户诉求匹配方案和案例。' },
    ],
    guides: [
      { key: 'g1', title: 'Plan 先行', description: 'Main Agent 先生成建议 Plan，不直接强制跑完整工作流。' },
      { key: 'g2', title: '用户裁剪', description: '每一步都能跳过、暂停或稍后继续，完成一部分也可以收口。' },
      { key: 'g3', title: '确认后再写回', description: '写主数据仍保留 preview、确认和审计。' },
    ],
    taskCards: [
      { key: 't1', title: '复合 Plan', status: '3 种', description: '最小录入、先查再建、完整闭环都由对话动态生成。', metric: '不作为场景入口' },
      { key: 't2', title: '销售主链路', status: '5 步', description: '客户分析到方案匹配按顺序可逐步进入。', metric: '5 个独立场景' },
      { key: 't3', title: '待确认写回', status: '5 个', description: '客户、商机和跟进记录的关键字段仍保留确认。', metric: '2 个高优先级' },
    ],
  },
  'customer-analysis': {
    key: 'customer-analysis',
    route: '/chat/customer-analysis',
    title: '客户分析',
    subtitle: '拜访前先看客户画像、关系人和商机盘点',
    headline: '客户分析是一个计划模板入口，公司研究只是它的外部供给来源之一。',
    description: '该入口会聚合客户、联系人、商机和历史跟进，再补充公司研究结果，输出可直接用于拜访前准备的客户分析卡片。',
    defaultInput: '/客户分析 星海精工股份',
    prompts: [
      { key: 'r1', label: '/客户分析 星海精工股份', description: '生成客户画像、关系人和商机判断。' },
      { key: 'r2', label: '/客户分析 远澜生物科技', description: '补齐初访背景和信息化改造线索。' },
      { key: 'r3', label: '/客户分析 星海精工股份 重点看关系人', description: '聚焦关键联系人和决策链。' },
    ],
    hotTopics: [
      { key: 'rh1', title: '客户分析会消费哪些输入？', description: '客户、联系人、商机、历史跟进和研究快照都会被读取。' },
      { key: 'rh2', title: '客户分析和公司研究是什么关系？', description: '前者是场景，后者是外部供给。' },
    ],
    guides: [
      { key: 'rg1', title: '主数据优先', description: '客户分析先吃记录系统数据，再叠加外部研究。' },
      { key: 'rg2', title: '来源透明', description: '外部研究只做补强，所有引用都带来源和更新时间。' },
    ],
    taskCards: [
      { key: 'rt1', title: '客户分析输入', status: '4 类', description: '客户、联系人、商机、历史跟进统一聚合。', metric: '外加公司研究供给' },
      { key: 'rt2', title: '研究快照复用', status: '82.4%', description: '已有研究结果会直接补入客户分析。', metric: '医药行业待增强' },
    ],
  },
  'conversation-understanding': {
    key: 'conversation-understanding',
    route: '/chat/conversation-understanding',
    title: '拜访会话理解',
    subtitle: '把录音和纪要转成事实、承诺与风险',
    headline: '拜访会话理解既能单独使用，也能被复合 Plan 动态加入。',
    description: '该场景围绕拜访录音和纪要，抽取关键事实、客户承诺事项和风险信号，为后续需求待办与问题陈述提供上游输入。',
    defaultInput: '/拜访会话理解 星海精工股份',
    prompts: [
      { key: 'v1', label: '/拜访会话理解 星海精工股份', description: '理解会话摘要、承诺事项和风险。' },
      { key: 'v2', label: '/拜访会话理解 远澜生物科技', description: '先把需求沟通纪要读清楚。' },
      { key: 'v3', label: '/拜访会话理解 星海精工股份 重点看风险', description: '优先抽取阻塞推进的信号。' },
    ],
    hotTopics: [
      { key: 'vh1', title: '会话理解要先做什么？', description: '先消费录音转写，再对齐客户和商机上下文。' },
      { key: 'vh2', title: '它和复合 Plan 的关系是什么？', description: '它可以作为录音处理 Plan 的分析节点，也可以被单独调用。' },
    ],
    guides: [
      { key: 'vg1', title: '先事实后判断', description: '先把客户说了什么讲清楚，再进入需求和问题拆解。' },
      { key: 'vg2', title: '输出可被下游复用', description: '会话理解结果会被需求待办和问题陈述继续消费。' },
    ],
    taskCards: [
      { key: 'vt1', title: '输出结构', status: '4 块', description: '会话摘要、关键事实、承诺事项、风险信号。', metric: '统一模板' },
      { key: 'vt2', title: '录音供给', status: '91.3%', description: '转写可用性保持稳定，能支撑后续理解。', metric: 'P95 12.4 分钟' },
    ],
  },
  'needs-todo-analysis': {
    key: 'needs-todo-analysis',
    route: '/chat/needs-todo-analysis',
    title: '客户需求工作待办分析',
    subtitle: '把需求和待办拆出来，推动从理解走向执行',
    headline: '需求待办分析是会话理解之后的执行中间层。',
    description: '该场景基于会话理解结果，把客户需求、客户侧待办、我方待办和责任归属拆清楚，方便销售会后真正推进动作。',
    defaultInput: '/客户需求工作待办分析 星海精工股份',
    prompts: [
      { key: 'n1', label: '/客户需求工作待办分析 星海精工股份', description: '拆出需求、我方待办和客户侧待办。' },
      { key: 'n2', label: '/客户需求工作待办分析 远澜生物科技', description: '整理初访后的需求收集与下一步动作。' },
      { key: 'n3', label: '/客户需求工作待办分析 星海精工股份 重点看责任人', description: '优先确认谁来做什么。' },
    ],
    hotTopics: [
      { key: 'nh1', title: '需求待办分析的上游是什么？', description: '默认消费拜访会话理解结果，也会读取商机和联系人上下文。' },
      { key: 'nh2', title: '它会直接写任务吗？', description: '当前先生成分析结果，正式写回仍然要确认。' },
    ],
    guides: [
      { key: 'ng1', title: '先识别需求，再拆动作', description: '不要把客户问题和我方待办混在一起。' },
      { key: 'ng2', title: '责任归属明确', description: '客户侧和我方动作分别呈现，避免会后失焦。' },
    ],
    taskCards: [
      { key: 'nt1', title: '输出视角', status: '3 类', description: '客户需求、客户侧待办、我方待办分开呈现。', metric: '责任归属可追踪' },
      { key: 'nt2', title: '复合 Plan 复用', status: '100%', description: '录音处理 Plan 可按需加入这一层。', metric: '也支持独立访问' },
    ],
  },
  'problem-statement': {
    key: 'problem-statement',
    route: '/chat/problem-statement',
    title: '问题陈述',
    subtitle: '把需求、约束与影响范围整理成统一问题定义',
    headline: '问题陈述是从需求走向方案沟通前最关键的整理节点。',
    description: '该场景会把需求待办分析结果收敛为问题背景、约束条件、影响范围和优先级，帮助销售和方案团队统一口径。',
    defaultInput: '/问题陈述 星海精工股份',
    prompts: [
      { key: 'ps1', label: '/问题陈述 星海精工股份', description: '基于需求待办结果形成统一问题定义。' },
      { key: 'ps2', label: '/问题陈述 远澜生物科技', description: '把初访需求整理成可讨论的问题陈述。' },
      { key: 'ps3', label: '/问题陈述 星海精工股份 重点看约束', description: '优先梳理交付、ROI 和迁移约束。' },
    ],
    hotTopics: [
      { key: 'ph1', title: '问题陈述和需求待办有什么区别？', description: '前者强调统一问题定义，后者强调执行动作。' },
      { key: 'ph2', title: '它适合什么阶段？', description: '适合需求澄清和客户价值定位前的口径统一。' },
    ],
    guides: [
      { key: 'pg1', title: '从动作回到问题', description: '先看客户到底想解决什么，再看我们怎么做。' },
      { key: 'pg2', title: '约束单独成块', description: '预算、周期、现有系统约束需要单独呈现。' },
    ],
    taskCards: [
      { key: 'pt1', title: '标准输出', status: '4 块', description: '问题背景、约束条件、影响范围、优先级。', metric: '适合内部评审' },
      { key: 'pt2', title: '下游衔接', status: '1 跳', description: '输出可直接进入客户价值定位。', metric: '减少重复组织语言' },
    ],
  },
  'value-positioning': {
    key: 'value-positioning',
    route: '/chat/value-positioning',
    title: '客户价值定位',
    subtitle: '把客户问题翻译成金蝶价值主张和推进话术',
    headline: '价值定位属于拜访后分析的收束一跳，把分析结论转成可进入方案推进的表达。',
    description: '该场景会消费客户分析、问题陈述和商机上下文，把客户问题映射成金蝶的价值表达、推进话术和方案推进输入建议。',
    defaultInput: '/客户价值定位 星海精工股份',
    prompts: [
      { key: 'vp1', label: '/客户价值定位 星海精工股份', description: '基于问题陈述输出价值主张和推进话术。' },
      { key: 'vp2', label: '/客户价值定位 远澜生物科技', description: '把数字化改造诉求翻译成金蝶价值表达。' },
      { key: 'vp3', label: '/客户价值定位 星海精工股份 重点看 ROI', description: '优先形成 ROI 和交付相关表述。' },
    ],
    hotTopics: [
      { key: 'vvh1', title: '价值定位吃哪些输入？', description: '问题陈述、客户分析、商机阶段和历史跟进都会被消费。' },
      { key: 'vvh2', title: '它输出给谁看？', description: '首先给销售自己用，也适合给方案同事对齐口径。' },
    ],
    guides: [
      { key: 'vvg1', title: '先问题，后价值', description: '不要直接堆产品能力，要先贴住客户问题。' },
      { key: 'vvg2', title: '输出可承接', description: '结果既能直接沟通，也要能被方案推进场景继续消费。' },
    ],
    taskCards: [
      { key: 'vvt1', title: '输出视角', status: '3 类', description: '价值主张、推进话术、推进输入建议。', metric: '贴近销售沟通' },
      { key: 'vvt2', title: '下游衔接', status: '1 跳', description: '可继续进入方案匹配。', metric: '减少重复组织语言' },
    ],
  },
  'solution-matching': {
    key: 'solution-matching',
    route: '/chat/solution-matching',
    title: '方案匹配',
    subtitle: '基于客户诉求匹配内部方案和案例',
    headline: '这一步不再继续拆问题，而是把客户诉求映射到可讨论的方案候选。',
    description: '该场景会消费问题陈述和客户价值定位，联动方案知识库和标杆案例库，形成下一轮方案推进建议。',
    defaultInput: '/方案匹配 星海精工股份',
    prompts: [
      { key: 'se1', label: '/方案匹配 星海精工股份', description: '基于当前客户诉求匹配内部方案和案例。' },
      { key: 'se2', label: '/方案匹配 远澜生物科技', description: '围绕数字化改造诉求生成方案建议。' },
      { key: 'se3', label: '/方案匹配 星海精工股份 重点看交付经验', description: '优先寻找类似案例和交付经验。' },
    ],
    hotTopics: [
      { key: 'seh1', title: '它和客户价值定位的关系是什么？', description: '价值定位先统一表达，方案匹配再组织方案和案例参考。' },
      { key: 'seh2', title: '这一步会产出什么？', description: '候选方案、匹配案例和下一轮推进建议。' },
    ],
    guides: [
      { key: 'seg1', title: '先贴诉求，再找资源', description: '从客户诉求和价值定位出发，不要直接堆公司已有材料。' },
      { key: 'seg2', title: '方案要能讨论', description: '输出要方便销售和方案同事围绕案例与路径推进下一轮沟通。' },
    ],
    taskCards: [
      { key: 'set1', title: '输出结构', status: '3 块', description: '候选方案、案例清单、推进建议。', metric: '服务下一轮方案推进' },
      { key: 'set2', title: '主要输入', status: '2 类', description: '问题陈述和客户价值定位是主输入。', metric: '补充内部知识资产' },
    ],
  },
  tasks: {
    key: 'tasks',
    route: '/chat/tasks',
    title: '我的任务',
    subtitle: '查看任务、资产与写回状态',
    headline: '把聊天里发生的事情变成可追踪的任务和资产。',
    description: '任务中心展示 traceId、taskId、实体锚点、下一步动作和场景状态，并能反查管理员后台。',
    defaultInput: '帮我汇总我今天所有待确认的任务。',
    prompts: [
      { key: 't1', label: '查看待确认写回', description: '聚焦客户、商机和跟进记录的确认动作。' },
      { key: 't2', label: '查看录音处理 Plan 进度', description: '按 traceId 追踪从 mp3 到问题陈述的进度。' },
      { key: 't3', label: '查看客户分析复用', description: '确认哪些任务已经复用客户分析结果。' },
    ],
    hotTopics: [
      { key: 'th1', title: '任务和场景是什么关系？', description: '场景触发任务，任务沉淀资产，资产再被后续场景复用。' },
      { key: 'th2', title: '怎么回后台排查？', description: '可直接带 traceId 回管理员后台看链路。' },
    ],
    guides: [
      { key: 'tg1', title: '任务可追踪', description: '每个任务都绑定 traceId / taskId。' },
      { key: 'tg2', title: '资产可回看', description: '录音、客户分析、问题陈述等结果都有资产记录。' },
    ],
    taskCards: [
      { key: 'tt1', title: '任务总数', status: '24 个', description: '当前个人范围内的活动任务。', metric: '3 个高优先级' },
      { key: 'tt2', title: '待确认写回', status: '5 个', description: '客户、商机和跟进记录的关键字段待确认。', metric: '2 个逾期' },
    ],
  },
};
